from app.schemas.practitioner.input import (
    PractitionerCreateSchema,
    PractitionerPatchSchema,
    PractitionerFullCreateSchema,
    PractitionerFullPatchSchema,
    PractitionerNameCreate,
    PractitionerNamePatch,
    PractitionerIdentifierCreate,
    PractitionerIdentifierPatch,
    PractitionerTelecomCreate,
    PractitionerTelecomPatch,
    PractitionerAddressCreate,
    PractitionerAddressPatch,
    PractitionerPhotoCreate,
    PractitionerPhotoPatch,
    QualificationIdentifierCreate,
    QualificationIdentifierPatch,
    PractitionerQualificationCreate,
    PractitionerQualificationPatch,
    PractitionerCommunicationCreate,
    PractitionerCommunicationPatch,
)
from app.schemas.practitioner.response import (
    FHIRPractitionerSchema,
    FHIRPractitionerBundle,
    FHIRPractitionerBundleEntry,
    FHIRAttachment,
    FHIRQualification,
    FHIRCommunication,
    PaginatedPractitionerResponse,
    PlainPractitionerResponse,
    PlainPractitionerName,
    PlainPractitionerIdentifier,
    PlainPractitionerTelecom,
    PlainPractitionerAddress,
    PlainPractitionerPhoto,
    PlainQualificationIdentifier,
    PlainQualification,
    PlainPractitionerCommunication,
    PractitionerNamesListResponse,
    PractitionerIdentifiersListResponse,
    PractitionerTelecomListResponse,
    PractitionerAddressesListResponse,
    PractitionerPhotosListResponse,
    PractitionerQualificationsListResponse,
    PractitionerCommunicationsListResponse,
    FHIRPractitionerNamesListResponse,
    FHIRPractitionerIdentifiersListResponse,
    FHIRPractitionerTelecomListResponse,
    FHIRPractitionerAddressesListResponse,
    FHIRPractitionerPhotosListResponse,
    FHIRPractitionerQualificationsListResponse,
    FHIRPractitionerCommunicationsListResponse,
)

__all__ = [
    # Input
    "PractitionerCreateSchema",
    "PractitionerPatchSchema",
    "PractitionerFullCreateSchema",
    "PractitionerFullPatchSchema",
    "PractitionerNameCreate", "PractitionerNamePatch",
    "PractitionerIdentifierCreate", "PractitionerIdentifierPatch",
    "PractitionerTelecomCreate", "PractitionerTelecomPatch",
    "PractitionerAddressCreate", "PractitionerAddressPatch",
    "PractitionerPhotoCreate", "PractitionerPhotoPatch",
    "QualificationIdentifierCreate", "QualificationIdentifierPatch",
    "PractitionerQualificationCreate", "PractitionerQualificationPatch",
    "PractitionerCommunicationCreate", "PractitionerCommunicationPatch",
    # Response
    "FHIRPractitionerSchema",
    "FHIRPractitionerBundle",
    "FHIRPractitionerBundleEntry",
    "FHIRAttachment",
    "FHIRQualification",
    "FHIRCommunication",
    "PaginatedPractitionerResponse",
    "PlainPractitionerResponse",
    "PlainPractitionerName",
    "PlainPractitionerIdentifier",
    "PlainPractitionerTelecom",
    "PlainPractitionerAddress",
    "PlainPractitionerPhoto",
    "PlainQualificationIdentifier",
    "PlainQualification",
    "PlainPractitionerCommunication",
    # Plain sub-resource list responses
    "PractitionerNamesListResponse",
    "PractitionerIdentifiersListResponse",
    "PractitionerTelecomListResponse",
    "PractitionerAddressesListResponse",
    "PractitionerPhotosListResponse",
    "PractitionerQualificationsListResponse",
    "PractitionerCommunicationsListResponse",
    # FHIR sub-resource list responses
    "FHIRPractitionerNamesListResponse",
    "FHIRPractitionerIdentifiersListResponse",
    "FHIRPractitionerTelecomListResponse",
    "FHIRPractitionerAddressesListResponse",
    "FHIRPractitionerPhotosListResponse",
    "FHIRPractitionerQualificationsListResponse",
    "FHIRPractitionerCommunicationsListResponse",
]
