from .address import (
    FHIRPatientAddressesListResponse,
    FHIRPatientAddressListItem,
    PatientAddressesListResponse,
    PlainPatientAddress,
)
from .communication import (
    FHIRPatientCommunication,
    FHIRPatientCommunicationListItem,
    FHIRPatientCommunicationsListResponse,
    PatientCommunicationsListResponse,
    PlainPatientCommunication,
)
from .contact import (
    FHIRPatientContact,
    FHIRPatientContactListItem,
    FHIRPatientContactsListResponse,
    PatientContactsListResponse,
    PlainContactRelationship,
    PlainContactTelecom,
    PlainPatientContact,
)
from .core import (
    FHIRPatientBundle,
    FHIRPatientBundleEntry,
    FHIRPatientCoreSchema,
    FHIRPatientSchema,
    PaginatedPatientResponse,
    PlainPatientCoreResponse,
    PlainPatientResponse,
)
from .general_practitioner import (
    FHIRPatientGeneralPractitionerListItem,
    FHIRPatientGeneralPractitionersListResponse,
    PatientGeneralPractitionersListResponse,
    PlainPatientGeneralPractitioner,
)
from .identifier import (
    FHIRPatientIdentifierListItem,
    FHIRPatientIdentifiersListResponse,
    PatientIdentifiersListResponse,
    PlainPatientIdentifier,
)
from .link import (
    FHIRPatientLink,
    FHIRPatientLinkListItem,
    FHIRPatientLinksListResponse,
    PatientLinksListResponse,
    PlainPatientLink,
)
from .name import (
    FHIRPatientNameListItem,
    FHIRPatientNamesListResponse,
    PatientNamesListResponse,
    PlainPatientName,
)
from .photo import (
    FHIRAttachment,
    FHIRPatientPhotoListItem,
    FHIRPatientPhotosListResponse,
    PatientPhotosListResponse,
    PlainPatientPhoto,
)
from .telecom import (
    FHIRPatientTelecomListItem,
    FHIRPatientTelecomListResponse,
    PatientTelecomListResponse,
    PlainPatientTelecom,
)

__all__ = [
    "FHIRAttachment",
    "FHIRPatientAddressesListResponse",
    "FHIRPatientAddressListItem",
    "FHIRPatientBundle",
    "FHIRPatientBundleEntry",
    "FHIRPatientCommunication",
    "FHIRPatientCommunicationListItem",
    "FHIRPatientCommunicationsListResponse",
    "FHIRPatientContact",
    "FHIRPatientContactListItem",
    "FHIRPatientContactsListResponse",
    "FHIRPatientCoreSchema",
    "FHIRPatientGeneralPractitionerListItem",
    "FHIRPatientGeneralPractitionersListResponse",
    "FHIRPatientIdentifierListItem",
    "FHIRPatientIdentifiersListResponse",
    "FHIRPatientLink",
    "FHIRPatientLinkListItem",
    "FHIRPatientLinksListResponse",
    "FHIRPatientNameListItem",
    "FHIRPatientNamesListResponse",
    "FHIRPatientPhotoListItem",
    "FHIRPatientPhotosListResponse",
    "FHIRPatientSchema",
    "FHIRPatientTelecomListItem",
    "FHIRPatientTelecomListResponse",
    "PaginatedPatientResponse",
    "PatientAddressesListResponse",
    "PatientCommunicationsListResponse",
    "PatientContactsListResponse",
    "PatientGeneralPractitionersListResponse",
    "PatientIdentifiersListResponse",
    "PatientLinksListResponse",
    "PatientNamesListResponse",
    "PatientPhotosListResponse",
    "PatientTelecomListResponse",
    "PlainContactRelationship",
    "PlainContactTelecom",
    "PlainPatientAddress",
    "PlainPatientCommunication",
    "PlainPatientContact",
    "PlainPatientCoreResponse",
    "PlainPatientGeneralPractitioner",
    "PlainPatientIdentifier",
    "PlainPatientLink",
    "PlainPatientName",
    "PlainPatientPhoto",
    "PlainPatientResponse",
    "PlainPatientTelecom",
]
