from app.schemas.patient.input import (
    PatientCreateSchema,
    PatientPatchSchema,
    NameCreate,
    NamePatch,
    IdentifierCreate,
    IdentifierPatch,
    TelecomCreate,
    TelecomPatch,
    AddressCreate,
    AddressPatch,
    PhotoCreate,
    PhotoPatch,
    ContactCreate,
    ContactPatch,
    ContactRelationshipCreate,
    ContactTelecomCreate,
    CommunicationCreate,
    CommunicationPatch,
    GeneralPractitionerCreate,
    GeneralPractitionerPatch,
    LinkCreate,
    LinkPatch,
)
from app.schemas.patient.response import (
    FHIRPatientSchema,
    FHIRPatientBundle,
    PaginatedPatientResponse,
    PlainPatientResponse,
    PlainPatientName,
    PlainPatientIdentifier,
    PlainPatientTelecom,
    PlainPatientAddress,
    PlainPatientPhoto,
    PlainPatientContact,
    PlainPatientCommunication,
    PlainPatientGeneralPractitioner,
    PlainPatientLink,
    FHIRPatientContact,
    FHIRPatientCommunication,
    FHIRPatientLink,
    FHIRAttachment,
    PatientNamesListResponse,
    PatientIdentifiersListResponse,
    PatientTelecomListResponse,
    PatientAddressesListResponse,
    PatientPhotosListResponse,
    PatientContactsListResponse,
    PatientCommunicationsListResponse,
    PatientGeneralPractitionersListResponse,
    PatientLinksListResponse,
    FHIRPatientNamesListResponse,
    FHIRPatientIdentifiersListResponse,
    FHIRPatientTelecomListResponse,
    FHIRPatientAddressesListResponse,
    FHIRPatientPhotosListResponse,
    FHIRPatientContactsListResponse,
    FHIRPatientCommunicationsListResponse,
    FHIRPatientGeneralPractitionersListResponse,
    FHIRPatientLinksListResponse,
)

__all__ = [
    # Input
    "PatientCreateSchema", "PatientPatchSchema",
    "NameCreate", "NamePatch",
    "IdentifierCreate", "IdentifierPatch",
    "TelecomCreate", "TelecomPatch",
    "AddressCreate", "AddressPatch",
    "PhotoCreate", "PhotoPatch",
    "ContactCreate", "ContactPatch",
    "ContactRelationshipCreate", "ContactTelecomCreate",
    "CommunicationCreate", "CommunicationPatch",
    "GeneralPractitionerCreate", "GeneralPractitionerPatch",
    "LinkCreate", "LinkPatch",
    # Response
    "FHIRPatientSchema", "FHIRPatientBundle", "PaginatedPatientResponse",
    "PlainPatientResponse", "PlainPatientName", "PlainPatientIdentifier",
    "PlainPatientTelecom", "PlainPatientAddress", "PlainPatientPhoto",
    "PlainPatientContact", "PlainPatientCommunication",
    "PlainPatientGeneralPractitioner", "PlainPatientLink",
    "FHIRPatientContact", "FHIRPatientCommunication", "FHIRPatientLink", "FHIRAttachment",
    # Plain sub-resource list responses
    "PatientNamesListResponse", "PatientIdentifiersListResponse",
    "PatientTelecomListResponse", "PatientAddressesListResponse",
    "PatientPhotosListResponse", "PatientContactsListResponse",
    "PatientCommunicationsListResponse", "PatientGeneralPractitionersListResponse",
    "PatientLinksListResponse",
    # FHIR sub-resource list responses
    "FHIRPatientNamesListResponse", "FHIRPatientIdentifiersListResponse",
    "FHIRPatientTelecomListResponse", "FHIRPatientAddressesListResponse",
    "FHIRPatientPhotosListResponse", "FHIRPatientContactsListResponse",
    "FHIRPatientCommunicationsListResponse", "FHIRPatientGeneralPractitionersListResponse",
    "FHIRPatientLinksListResponse",
]
