from app.schemas.common.fhir import (
    FHIRAddress,
    FHIRBundle,
    FHIRBundleEntry,
    FHIRCoding,
    FHIRCodeableConcept,
    FHIRContactPoint,
    FHIRHumanName,
    FHIRIdentifier,
    FHIRPeriod,
    FHIRReference,
    PlainCoding,
    PlainIdentifier,
    PlainIdentifierType,
    PlainReasonCode,
)
from app.schemas.patient.response import (
    FHIRPatientSchema, FHIRPatientCoreSchema, FHIRPatientBundle, PaginatedPatientResponse,
    PlainPatientResponse, PlainPatientCoreResponse, PlainPatientName, PlainPatientTelecom, PlainPatientAddress,
    PlainPatientPhoto, PlainPatientContact, PlainPatientCommunication,
    PlainPatientGeneralPractitioner, PlainPatientLink,
    PatientNamesListResponse, PatientIdentifiersListResponse,
    PatientTelecomListResponse, PatientAddressesListResponse,
    PatientPhotosListResponse, PatientContactsListResponse,
    PatientCommunicationsListResponse, PatientGeneralPractitionersListResponse,
    PatientLinksListResponse,
    FHIRPatientNamesListResponse, FHIRPatientIdentifiersListResponse,
    FHIRPatientTelecomListResponse, FHIRPatientAddressesListResponse,
    FHIRPatientPhotosListResponse, FHIRPatientContactsListResponse,
    FHIRPatientCommunicationsListResponse, FHIRPatientGeneralPractitionersListResponse,
    FHIRPatientLinksListResponse,
)
from app.schemas.practitioner.response import (
    FHIRPractitionerSchema, FHIRPractitionerBundle, FHIRPractitionerBundleEntry,
    FHIRAttachment, FHIRQualification, FHIRCommunication,
    PaginatedPractitionerResponse, PlainPractitionerResponse,
    PlainPractitionerName, PlainPractitionerIdentifier,
    PlainPractitionerTelecom, PlainPractitionerAddress,
    PlainPractitionerPhoto, PlainQualification, PlainPractitionerCommunication,
    PractitionerNamesListResponse, PractitionerIdentifiersListResponse,
    PractitionerTelecomListResponse, PractitionerAddressesListResponse,
    PractitionerPhotosListResponse, PractitionerQualificationsListResponse,
    PractitionerCommunicationsListResponse,
    FHIRPractitionerNamesListResponse, FHIRPractitionerIdentifiersListResponse,
    FHIRPractitionerTelecomListResponse, FHIRPractitionerAddressesListResponse,
    FHIRPractitionerPhotosListResponse, FHIRPractitionerQualificationsListResponse,
    FHIRPractitionerCommunicationsListResponse,
)
from app.schemas.encounter.response import (
    FHIREncounterSchema, FHIREncounterBundle, FHIREncounterBundleEntry,
    FHIREncounterStatusHistory, FHIREncounterClassHistory,
    FHIREncounterParticipant, FHIREncounterDiagnosis,
    FHIREncounterHospitalization, FHIREncounterLocation,
    PaginatedEncounterResponse, PlainEncounterResponse,
    PlainEncounterIdentifier, PlainEncounterStatusHistory, PlainEncounterClassHistory,
    PlainEncounterType, PlainEncounterEpisodeOfCare, PlainEncounterBasedOn,
    PlainEncounterParticipantType, PlainEncounterParticipant,
    PlainEncounterAppointmentRef,
    PlainEncounterReasonCode, PlainEncounterReasonReference,
    PlainEncounterDiagnosis,
    PlainEncounterAccount, PlainEncounterHospitalization, PlainEncounterLocation,
    PlainEncounterLength, PlainEncounterCodeableConcept,
)
from app.schemas.appointment.response import (
    FHIRAppointmentSchema, FHIRAppointmentBundle, FHIRAppointmentBundleEntry,
    FHIRAppointmentParticipant,
    PaginatedAppointmentResponse, PlainAppointmentResponse,
    PlainAppointmentIdentifier,
    PlainAppointmentServiceCategory, PlainAppointmentServiceType, PlainAppointmentSpecialty,
    PlainAppointmentReasonCode, PlainAppointmentReasonReference,
    PlainAppointmentSupportingInformation, PlainAppointmentSlot, PlainAppointmentBasedOn,
    PlainAppointmentParticipantType, PlainAppointmentParticipant, PlainAppointmentRequestedPeriod,
    PlainWeeklyTemplate, PlainMonthlyTemplate, PlainYearlyTemplate, PlainRecurrenceTemplate,
)
from app.schemas.condition.response import (
    FHIRConditionSchema,
    FHIRConditionBundle,
    FHIRConditionBundleEntry,
    FHIRConditionStage,
    FHIRConditionEvidence,
    FHIRAnnotation,
    PaginatedConditionResponse,
    PlainConditionResponse,
    PlainConditionIdentifier,
    PlainConditionCategory,
    PlainConditionBodySite,
    PlainConditionStageAssessment,
    PlainConditionStage,
    PlainConditionEvidenceCode,
    PlainConditionEvidenceDetail,
    PlainConditionEvidence,
    PlainConditionNote,
)
from app.schemas.questionnaire_response.response import (
    FHIRQuestionnaireResponseSchema, FHIRQuestionnaireResponseBundle,
    FHIRQuestionnaireResponseBundleEntry, FHIRQRItem, FHIRAnswer,
    FHIRAnswerCoding, FHIRAnswerQuantity, FHIRAnswerValueReference, FHIRAnswerAttachment,
    PaginatedQuestionnaireResponseResponse, PlainQuestionnaireResponse,
    PlainQRItem, PlainQRAnswer, PlainQRBasedOn, PlainQRPartOf,
    PlainAnswerCoding, PlainAnswerQuantity, PlainAnswerAttachment,
)

__all__ = [
    # Common FHIR
    "FHIRAddress", "FHIRBundle", "FHIRBundleEntry", "FHIRCoding", "FHIRCodeableConcept",
    "FHIRContactPoint", "FHIRHumanName", "FHIRIdentifier", "FHIRPeriod", "FHIRReference",
    "PlainCoding", "PlainIdentifier", "PlainIdentifierType", "PlainReasonCode",
    # Patient
    "FHIRPatientSchema", "FHIRPatientCoreSchema", "FHIRPatientBundle", "PaginatedPatientResponse",
    "PlainPatientResponse", "PlainPatientCoreResponse", "PlainPatientName", "PlainPatientTelecom", "PlainPatientAddress",
    "PlainPatientPhoto", "PlainPatientContact", "PlainPatientCommunication",
    "PlainPatientGeneralPractitioner", "PlainPatientLink",
    "PatientNamesListResponse", "PatientIdentifiersListResponse",
    "PatientTelecomListResponse", "PatientAddressesListResponse",
    "PatientPhotosListResponse", "PatientContactsListResponse",
    "PatientCommunicationsListResponse", "PatientGeneralPractitionersListResponse",
    "PatientLinksListResponse",
    "FHIRPatientNamesListResponse", "FHIRPatientIdentifiersListResponse",
    "FHIRPatientTelecomListResponse", "FHIRPatientAddressesListResponse",
    "FHIRPatientPhotosListResponse", "FHIRPatientContactsListResponse",
    "FHIRPatientCommunicationsListResponse", "FHIRPatientGeneralPractitionersListResponse",
    "FHIRPatientLinksListResponse",
    # Practitioner
    "FHIRPractitionerSchema", "FHIRPractitionerBundle", "FHIRPractitionerBundleEntry",
    "FHIRAttachment", "FHIRQualification", "FHIRCommunication",
    "PaginatedPractitionerResponse", "PlainPractitionerResponse",
    "PlainPractitionerName", "PlainPractitionerIdentifier",
    "PlainPractitionerTelecom", "PlainPractitionerAddress",
    "PlainPractitionerPhoto", "PlainQualification", "PlainPractitionerCommunication",
    "PractitionerNamesListResponse", "PractitionerIdentifiersListResponse",
    "PractitionerTelecomListResponse", "PractitionerAddressesListResponse",
    "PractitionerPhotosListResponse", "PractitionerQualificationsListResponse",
    "PractitionerCommunicationsListResponse",
    "FHIRPractitionerNamesListResponse", "FHIRPractitionerIdentifiersListResponse",
    "FHIRPractitionerTelecomListResponse", "FHIRPractitionerAddressesListResponse",
    "FHIRPractitionerPhotosListResponse", "FHIRPractitionerQualificationsListResponse",
    "FHIRPractitionerCommunicationsListResponse",
    # Encounter
    "FHIREncounterSchema", "FHIREncounterBundle", "FHIREncounterBundleEntry",
    "FHIREncounterStatusHistory", "FHIREncounterClassHistory",
    "FHIREncounterParticipant", "FHIREncounterDiagnosis",
    "FHIREncounterHospitalization", "FHIREncounterLocation",
    "PaginatedEncounterResponse", "PlainEncounterResponse",
    "PlainEncounterIdentifier", "PlainEncounterStatusHistory", "PlainEncounterClassHistory",
    "PlainEncounterType", "PlainEncounterEpisodeOfCare", "PlainEncounterBasedOn",
    "PlainEncounterParticipantType", "PlainEncounterParticipant",
    "PlainEncounterAppointmentRef",
    "PlainEncounterReasonCode", "PlainEncounterReasonReference",
    "PlainEncounterDiagnosis",
    "PlainEncounterAccount", "PlainEncounterHospitalization", "PlainEncounterLocation",
    "PlainEncounterLength", "PlainEncounterCodeableConcept",
    # Appointment
    "FHIRAppointmentSchema", "FHIRAppointmentBundle", "FHIRAppointmentBundleEntry",
    "FHIRAppointmentParticipant",
    "PaginatedAppointmentResponse", "PlainAppointmentResponse",
    "PlainAppointmentIdentifier",
    "PlainAppointmentServiceCategory", "PlainAppointmentServiceType", "PlainAppointmentSpecialty",
    "PlainAppointmentReasonCode", "PlainAppointmentReasonReference",
    "PlainAppointmentSupportingInformation", "PlainAppointmentSlot", "PlainAppointmentBasedOn",
    "PlainAppointmentParticipantType", "PlainAppointmentParticipant", "PlainAppointmentRequestedPeriod",
    "PlainWeeklyTemplate", "PlainMonthlyTemplate", "PlainYearlyTemplate", "PlainRecurrenceTemplate",
    # Condition
    "FHIRConditionSchema", "FHIRConditionBundle", "FHIRConditionBundleEntry",
    "FHIRConditionStage", "FHIRConditionEvidence", "FHIRAnnotation",
    "PaginatedConditionResponse", "PlainConditionResponse",
    "PlainConditionIdentifier", "PlainConditionCategory", "PlainConditionBodySite",
    "PlainConditionStageAssessment", "PlainConditionStage",
    "PlainConditionEvidenceCode", "PlainConditionEvidenceDetail",
    "PlainConditionEvidence", "PlainConditionNote",
    # QuestionnaireResponse
    "FHIRQuestionnaireResponseSchema", "FHIRQuestionnaireResponseBundle",
    "FHIRQuestionnaireResponseBundleEntry", "FHIRQRItem", "FHIRAnswer",
    "FHIRAnswerCoding", "FHIRAnswerQuantity", "FHIRAnswerValueReference", "FHIRAnswerAttachment",
    "PaginatedQuestionnaireResponseResponse", "PlainQuestionnaireResponse",
    "PlainQRItem", "PlainQRAnswer", "PlainQRBasedOn", "PlainQRPartOf",
    "PlainAnswerCoding", "PlainAnswerQuantity", "PlainAnswerAttachment",
]
