"""practitioner_role_rework

Revision ID: 119f6f93474c
Revises: 418c5a532556
Create Date: 2026-09-02 17:56:48.950449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '119f6f93474c'
down_revision: Union[str, None] = '418c5a532556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practitioner_role_available_time',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('days_of_week', sa.Text(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('available_start_time', sa.Time(), nullable=True),
    sa.Column('available_end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_available_time_practitioner_role_id'), 'practitioner_role_available_time', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_not_available',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('during_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('during_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_not_available_practitioner_role_id'), 'practitioner_role_not_available', ['practitioner_role_id'], unique=False)
    op.drop_index(op.f('ix_practitioner_role_availability_time_practitioner_role_id'), table_name='practitioner_role_availability_time')
    op.drop_table('practitioner_role_availability_time')
    op.drop_index(op.f('ix_practitioner_role_not_available_time_practitioner_role_id'), table_name='practitioner_role_not_available_time')
    op.drop_table('practitioner_role_not_available_time')
    # op.add_column doesn't auto-create a brand-new Postgres enum type the way
    # op.create_table sometimes does — create it explicitly first.
    op.execute("CREATE TYPE practitioner_role_practitioner_reference_type AS ENUM ('Practitioner')")
    op.add_column('practitioner_role', sa.Column('practitioner_type', postgresql.ENUM('Practitioner', name='practitioner_role_practitioner_reference_type', create_type=False), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role', sa.Column('organization_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('practitioner_role', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('practitioner_role_pub_seq'::regclass)"))
    op.alter_column('practitioner_role', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_role', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('practitioner_role', 'practitioner_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('practitioner_role', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('practitioner_role', 'availability_exceptions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('practitioner_role', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_practitioner_role_organization_id'), table_name='practitioner_role')
    op.drop_index(op.f('ix_practitioner_role_practitioner_id'), table_name='practitioner_role')
    op.drop_index(op.f('ix_practitioner_role_user_id'), table_name='practitioner_role')
    op.drop_constraint(op.f('practitioner_role_practitioner_id_fkey'), 'practitioner_role', type_='foreignkey')
    op.drop_constraint(op.f('practitioner_role_organization_id_fkey'), 'practitioner_role', type_='foreignkey')
    op.drop_column('practitioner_role', 'user_id')
    op.add_column('practitioner_role_code', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_code', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_code', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_code', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_code', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_code', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_code', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_code', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_code', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_endpoint', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_endpoint', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_endpoint', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_endpoint', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Renamed PG enum type — alter_column can't cast to a not-yet-existing
    # type name, so rename the existing type in place instead (values unchanged).
    op.execute('ALTER TYPE pr_endpoint_ref_type RENAME TO practitioner_role_endpoint_reference_type')
    op.alter_column('practitioner_role_endpoint', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_unique_constraint('uq_practitioner_role_endpoint_reference', 'practitioner_role_endpoint', ['practitioner_role_id', 'reference_type', 'reference_id'])
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_healthcare_service', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_healthcare_service', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_healthcare_service', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_healthcare_service', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_healthcare_service', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Renamed PG enum type — see the endpoint rename above.
    op.execute('ALTER TYPE pr_healthcare_service_ref_type RENAME TO practitioner_role_healthcare_service_reference_type')
    op.drop_index(op.f('ix_practitioner_role_healthcare_service_reference_id'), table_name='practitioner_role_healthcare_service')
    op.create_unique_constraint('uq_practitioner_role_healthcare_service_reference', 'practitioner_role_healthcare_service', ['practitioner_role_id', 'reference_type', 'reference_id'])
    op.drop_constraint(op.f('practitioner_role_healthcare_service_reference_id_fkey'), 'practitioner_role_healthcare_service', type_='foreignkey')
    op.add_column('practitioner_role_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_type', postgresql.ENUM('Organization', name='organization_reference_type', create_type=False), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_id', sa.BigInteger(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_identifier', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_role_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_practitioner_role_identifier_system_value', 'practitioner_role_identifier', ['system', 'value'])
    op.drop_column('practitioner_role_identifier', 'assigner')
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_location', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_location', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_location', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_location', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_location', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Renamed PG enum type — see the endpoint rename above.
    op.execute('ALTER TYPE pr_location_ref_type RENAME TO practitioner_role_location_reference_type')
    op.alter_column('practitioner_role_location', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_practitioner_role_location_reference_id'), table_name='practitioner_role_location')
    op.create_unique_constraint('uq_practitioner_role_location_reference', 'practitioner_role_location', ['practitioner_role_id', 'reference_type', 'reference_id'])
    op.drop_constraint(op.f('practitioner_role_location_reference_id_fkey'), 'practitioner_role_location', type_='foreignkey')
    op.add_column('practitioner_role_specialty', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('practitioner_role_specialty', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_role_specialty', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_specialty', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_specialty', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_specialty', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_specialty', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_specialty', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_specialty', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_role_telecom', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_role_telecom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_role_telecom', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_role_telecom', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_role_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_role_telecom', 'practitioner_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_role_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_role_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False)
    op.alter_column('practitioner_role_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # day_of_week was only ever used by the now-dropped
    # practitioner_role_availability_time.days_of_week ARRAY(Enum) column —
    # days_of_week is comma-separated Text now, so this type is orphaned.
    op.execute('DROP TYPE IF EXISTS day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practitioner_role_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=True)
    op.alter_column('practitioner_role_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_telecom', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_telecom', 'updated_by')
    op.drop_column('practitioner_role_telecom', 'created_by')
    op.drop_column('practitioner_role_telecom', 'updated_at')
    op.drop_column('practitioner_role_telecom', 'created_at')
    op.alter_column('practitioner_role_specialty', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_specialty', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_specialty', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_specialty', 'updated_by')
    op.drop_column('practitioner_role_specialty', 'created_by')
    op.drop_column('practitioner_role_specialty', 'updated_at')
    op.drop_column('practitioner_role_specialty', 'created_at')
    op.drop_column('practitioner_role_specialty', 'coding_user_selected')
    op.drop_column('practitioner_role_specialty', 'coding_version')
    op.create_foreign_key(op.f('practitioner_role_location_reference_id_fkey'), 'practitioner_role_location', 'location', ['reference_id'], ['id'])
    op.drop_constraint('uq_practitioner_role_location_reference', 'practitioner_role_location', type_='unique')
    op.create_index(op.f('ix_practitioner_role_location_reference_id'), 'practitioner_role_location', ['reference_id'], unique=False)
    op.alter_column('practitioner_role_location', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.execute('ALTER TYPE practitioner_role_location_reference_type RENAME TO pr_location_ref_type')
    op.alter_column('practitioner_role_location', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_location', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_location', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_location', 'updated_by')
    op.drop_column('practitioner_role_location', 'created_by')
    op.drop_column('practitioner_role_location', 'updated_at')
    op.drop_column('practitioner_role_location', 'created_at')
    op.drop_column('practitioner_role_location', 'reference_identifier_period_end')
    op.drop_column('practitioner_role_location', 'reference_identifier_period_start')
    op.drop_column('practitioner_role_location', 'reference_identifier_value')
    op.drop_column('practitioner_role_location', 'reference_identifier_system')
    op.drop_column('practitioner_role_location', 'reference_identifier_type_user_selected')
    op.drop_column('practitioner_role_location', 'reference_identifier_type_text')
    op.drop_column('practitioner_role_location', 'reference_identifier_type_display')
    op.drop_column('practitioner_role_location', 'reference_identifier_type_code')
    op.drop_column('practitioner_role_location', 'reference_identifier_type_version')
    op.drop_column('practitioner_role_location', 'reference_identifier_type_system')
    op.drop_column('practitioner_role_location', 'reference_identifier_use')
    op.add_column('practitioner_role_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_practitioner_role_identifier_system_value', 'practitioner_role_identifier', type_='unique')
    op.alter_column('practitioner_role_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_identifier', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_identifier', 'updated_by')
    op.drop_column('practitioner_role_identifier', 'created_by')
    op.drop_column('practitioner_role_identifier', 'updated_at')
    op.drop_column('practitioner_role_identifier', 'created_at')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_period_end')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_period_start')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_value')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_system')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_type_text')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_type_display')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_type_code')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_type_version')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_type_system')
    op.drop_column('practitioner_role_identifier', 'assigner_identifier_use')
    op.drop_column('practitioner_role_identifier', 'assigner_display')
    op.drop_column('practitioner_role_identifier', 'assigner_id')
    op.drop_column('practitioner_role_identifier', 'assigner_type')
    op.drop_column('practitioner_role_identifier', 'type_user_selected')
    op.drop_column('practitioner_role_identifier', 'type_version')
    op.create_foreign_key(op.f('practitioner_role_healthcare_service_reference_id_fkey'), 'practitioner_role_healthcare_service', 'healthcare_service', ['reference_id'], ['id'])
    op.drop_constraint('uq_practitioner_role_healthcare_service_reference', 'practitioner_role_healthcare_service', type_='unique')
    op.create_index(op.f('ix_practitioner_role_healthcare_service_reference_id'), 'practitioner_role_healthcare_service', ['reference_id'], unique=False)
    op.execute('ALTER TYPE practitioner_role_healthcare_service_reference_type RENAME TO pr_healthcare_service_ref_type')
    op.alter_column('practitioner_role_healthcare_service', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_healthcare_service', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_healthcare_service', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_healthcare_service', 'updated_by')
    op.drop_column('practitioner_role_healthcare_service', 'created_by')
    op.drop_column('practitioner_role_healthcare_service', 'updated_at')
    op.drop_column('practitioner_role_healthcare_service', 'created_at')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_period_end')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_period_start')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_value')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_system')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_type_user_selected')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_type_text')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_type_display')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_type_code')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_type_version')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_type_system')
    op.drop_column('practitioner_role_healthcare_service', 'reference_identifier_use')
    op.drop_constraint('uq_practitioner_role_endpoint_reference', 'practitioner_role_endpoint', type_='unique')
    op.alter_column('practitioner_role_endpoint', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.execute('ALTER TYPE practitioner_role_endpoint_reference_type RENAME TO pr_endpoint_ref_type')
    op.alter_column('practitioner_role_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_endpoint', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_endpoint', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_endpoint', 'updated_by')
    op.drop_column('practitioner_role_endpoint', 'created_by')
    op.drop_column('practitioner_role_endpoint', 'updated_at')
    op.drop_column('practitioner_role_endpoint', 'created_at')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_period_end')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_period_start')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_value')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_system')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_type_user_selected')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_type_text')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_type_display')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_type_code')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_type_version')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_type_system')
    op.drop_column('practitioner_role_endpoint', 'reference_identifier_use')
    op.alter_column('practitioner_role_code', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role_code', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_role_code', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role_code', 'updated_by')
    op.drop_column('practitioner_role_code', 'created_by')
    op.drop_column('practitioner_role_code', 'updated_at')
    op.drop_column('practitioner_role_code', 'created_at')
    op.drop_column('practitioner_role_code', 'coding_user_selected')
    op.drop_column('practitioner_role_code', 'coding_version')
    op.add_column('practitioner_role', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('practitioner_role_organization_id_fkey'), 'practitioner_role', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('practitioner_role_practitioner_id_fkey'), 'practitioner_role', 'practitioner', ['practitioner_id'], ['id'])
    op.create_index(op.f('ix_practitioner_role_user_id'), 'practitioner_role', ['user_id'], unique=False)
    op.create_index(op.f('ix_practitioner_role_practitioner_id'), 'practitioner_role', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_practitioner_role_organization_id'), 'practitioner_role', ['organization_id'], unique=False)
    op.alter_column('practitioner_role', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role', 'availability_exceptions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('practitioner_role', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('practitioner_role', 'practitioner_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('practitioner_role', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('practitioner_role', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_role', 'practitioner_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('practitioner_role_pub_seq'::regclass)"))
    op.alter_column('practitioner_role', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('practitioner_role', 'organization_identifier_period_end')
    op.drop_column('practitioner_role', 'organization_identifier_period_start')
    op.drop_column('practitioner_role', 'organization_identifier_value')
    op.drop_column('practitioner_role', 'organization_identifier_system')
    op.drop_column('practitioner_role', 'organization_identifier_type_user_selected')
    op.drop_column('practitioner_role', 'organization_identifier_type_text')
    op.drop_column('practitioner_role', 'organization_identifier_type_display')
    op.drop_column('practitioner_role', 'organization_identifier_type_code')
    op.drop_column('practitioner_role', 'organization_identifier_type_version')
    op.drop_column('practitioner_role', 'organization_identifier_type_system')
    op.drop_column('practitioner_role', 'organization_identifier_use')
    op.drop_column('practitioner_role', 'practitioner_identifier_period_end')
    op.drop_column('practitioner_role', 'practitioner_identifier_period_start')
    op.drop_column('practitioner_role', 'practitioner_identifier_value')
    op.drop_column('practitioner_role', 'practitioner_identifier_system')
    op.drop_column('practitioner_role', 'practitioner_identifier_type_user_selected')
    op.drop_column('practitioner_role', 'practitioner_identifier_type_text')
    op.drop_column('practitioner_role', 'practitioner_identifier_type_display')
    op.drop_column('practitioner_role', 'practitioner_identifier_type_code')
    op.drop_column('practitioner_role', 'practitioner_identifier_type_version')
    op.drop_column('practitioner_role', 'practitioner_identifier_type_system')
    op.drop_column('practitioner_role', 'practitioner_identifier_use')
    op.drop_column('practitioner_role', 'practitioner_type')
    op.execute('DROP TYPE IF EXISTS practitioner_role_practitioner_reference_type')
    op.create_table('practitioner_role_not_available_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('during_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('during_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], name=op.f('practitioner_role_not_available_time_practitioner_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_not_available_time_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_not_available_time_practitioner_role_id'), 'practitioner_role_not_available_time', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_availability_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('days_of_week', postgresql.ARRAY(postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='day_of_week')), autoincrement=False, nullable=True),
    sa.Column('all_day', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('available_start_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('available_end_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], name=op.f('practitioner_role_availability_time_practitioner_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_availability_time_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_availability_time_practitioner_role_id'), 'practitioner_role_availability_time', ['practitioner_role_id'], unique=False)
    op.drop_index(op.f('ix_practitioner_role_not_available_practitioner_role_id'), table_name='practitioner_role_not_available')
    op.drop_table('practitioner_role_not_available')
    op.drop_index(op.f('ix_practitioner_role_available_time_practitioner_role_id'), table_name='practitioner_role_available_time')
    op.drop_table('practitioner_role_available_time')
    # ### end Alembic commands ###
