"""organization_rework

Revision ID: 275311fe9686
Revises: 0a0625d11afb
Create Date: 2026-10-06 18:27:03.842225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '275311fe9686'
down_revision: Union[str, None] = '0a0625d11afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed ~34 `CREATE SEQUENCE IF NOT EXISTS`
    # statements here for every other resource's _pub_seq (allergy_intolerance,
    # appointment, claim, ...). Verified against the live DB directly — every
    # one of those sequences already exists; this was a false positive (Alembic
    # doesn't reliably track standalone `Sequence` objects against what's
    # already reflected in the database). Removed to keep this migration
    # scoped to the actual Organization rework, per explicit decision not to
    # touch any other resource's migration history in this pass.
    op.create_table('organization_contact_purpose_coding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('user_selected', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['organization_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_contact_purpose_coding_contact_id'), 'organization_contact_purpose_coding', ['contact_id'], unique=False)
    op.create_index(op.f('ix_organization_contact_purpose_coding_created_at'), 'organization_contact_purpose_coding', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_contact_purpose_coding_tenant_id'), 'organization_contact_purpose_coding', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_contact_purpose_coding_updated_at'), 'organization_contact_purpose_coding', ['updated_at'], unique=False)
    op.create_table('organization_identifier_type_coding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_identifier_id', sa.BigInteger(), nullable=False),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('user_selected', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_identifier_id'], ['organization_identifier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_identifier_type_coding_created_at'), 'organization_identifier_type_coding', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_identifier_type_coding_organization_identifier_id'), 'organization_identifier_type_coding', ['organization_identifier_id'], unique=False)
    op.create_index(op.f('ix_organization_identifier_type_coding_tenant_id'), 'organization_identifier_type_coding', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_identifier_type_coding_updated_at'), 'organization_identifier_type_coding', ['updated_at'], unique=False)
    op.create_table('organization_type_coding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_type_id', sa.BigInteger(), nullable=False),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('user_selected', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_type_id'], ['organization_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_type_coding_created_at'), 'organization_type_coding', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_type_coding_organization_type_id'), 'organization_type_coding', ['organization_type_id'], unique=False)
    op.create_index(op.f('ix_organization_type_coding_tenant_id'), 'organization_type_coding', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_type_coding_updated_at'), 'organization_type_coding', ['updated_at'], unique=False)
    op.add_column('organization', sa.Column('partof_reference', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('extension', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('organization', sa.Column('tenant_id', sa.String(), nullable=False))
    op.alter_column('organization', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_organization_org_id'), table_name='organization')
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_tenant_id'), 'organization', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_updated_at'), 'organization', ['updated_at'], unique=False)
    op.drop_column('organization', 'org_id')
    op.add_column('organization_address', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_address', sa.Column('tenant_id', sa.String(), nullable=False))
    op.alter_column('organization_address', 'type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type'),
               nullable=True)
    op.alter_column('organization_address', 'line',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               # Table is empty (verified before running this migration) — no
               # real data to convert, so NULL is a safe USING expression.
               # Not an automatic cast in Postgres, hence the explicit clause.
               postgresql_using='NULL::character varying[]')
    op.alter_column('organization_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_organization_address_organization_id'), table_name='organization_address')
    op.create_index(op.f('ix_organization_address_created_at'), 'organization_address', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_address_organization_pk'), 'organization_address', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_address_tenant_id'), 'organization_address', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_address_updated_at'), 'organization_address', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_address_organization_id_fkey'), 'organization_address', type_='foreignkey')
    op.create_foreign_key(None, 'organization_address', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_address', 'org_id')
    op.drop_column('organization_address', 'organization_id')
    op.add_column('organization_alias', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_alias', sa.Column('tenant_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_organization_alias_organization_id'), table_name='organization_alias')
    op.create_index(op.f('ix_organization_alias_created_at'), 'organization_alias', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_alias_organization_pk'), 'organization_alias', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_alias_tenant_id'), 'organization_alias', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_alias_updated_at'), 'organization_alias', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_alias_organization_id_fkey'), 'organization_alias', type_='foreignkey')
    op.create_foreign_key(None, 'organization_alias', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_alias', 'org_id')
    op.drop_column('organization_alias', 'organization_id')
    op.add_column('organization_contact', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_contact', sa.Column('tenant_id', sa.String(), nullable=False))
    op.alter_column('organization_contact', 'name_given',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='NULL::character varying[]')
    op.alter_column('organization_contact', 'name_prefix',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='NULL::character varying[]')
    op.alter_column('organization_contact', 'name_suffix',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='NULL::character varying[]')
    op.alter_column('organization_contact', 'address_type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type'),
               nullable=True)
    op.alter_column('organization_contact', 'address_line',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='NULL::character varying[]')
    op.alter_column('organization_contact', 'address_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_organization_contact_organization_id'), table_name='organization_contact')
    op.create_index(op.f('ix_organization_contact_created_at'), 'organization_contact', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_contact_organization_pk'), 'organization_contact', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_contact_tenant_id'), 'organization_contact', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_contact_updated_at'), 'organization_contact', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_contact_organization_id_fkey'), 'organization_contact', type_='foreignkey')
    op.create_foreign_key(None, 'organization_contact', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_contact', 'purpose_version')
    op.drop_column('organization_contact', 'org_id')
    op.drop_column('organization_contact', 'organization_id')
    op.drop_column('organization_contact', 'purpose_code')
    op.drop_column('organization_contact', 'purpose_display')
    op.drop_column('organization_contact', 'purpose_user_selected')
    op.drop_column('organization_contact', 'purpose_system')
    op.add_column('organization_contact_telecom', sa.Column('tenant_id', sa.String(), nullable=False))
    op.alter_column('organization_contact_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=True)
    op.alter_column('organization_contact_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_organization_contact_telecom_created_at'), 'organization_contact_telecom', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_contact_telecom_tenant_id'), 'organization_contact_telecom', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_contact_telecom_updated_at'), 'organization_contact_telecom', ['updated_at'], unique=False)
    op.drop_column('organization_contact_telecom', 'org_id')
    op.add_column('organization_endpoint', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_endpoint', sa.Column('reference_reference', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('tenant_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_organization_endpoint_organization_id'), table_name='organization_endpoint')
    op.drop_constraint(op.f('uq_organization_endpoint_reference'), 'organization_endpoint', type_='unique')
    op.create_index(op.f('ix_organization_endpoint_created_at'), 'organization_endpoint', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_endpoint_organization_pk'), 'organization_endpoint', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_endpoint_tenant_id'), 'organization_endpoint', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_endpoint_updated_at'), 'organization_endpoint', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_endpoint_organization_id_fkey'), 'organization_endpoint', type_='foreignkey')
    op.create_foreign_key(None, 'organization_endpoint', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_endpoint', 'org_id')
    op.drop_column('organization_endpoint', 'organization_id')
    op.add_column('organization_identifier', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_identifier', sa.Column('assigner_reference', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('tenant_id', sa.String(), nullable=False))
    op.alter_column('organization_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_organization_identifier_organization_id'), table_name='organization_identifier')
    op.drop_constraint(op.f('uq_organization_identifier_system_value'), 'organization_identifier', type_='unique')
    op.create_index(op.f('ix_organization_identifier_created_at'), 'organization_identifier', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_identifier_organization_pk'), 'organization_identifier', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_identifier_tenant_id'), 'organization_identifier', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_identifier_updated_at'), 'organization_identifier', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_identifier_organization_id_fkey'), 'organization_identifier', type_='foreignkey')
    op.create_foreign_key(None, 'organization_identifier', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_identifier', 'type_user_selected')
    op.drop_column('organization_identifier', 'org_id')
    op.drop_column('organization_identifier', 'organization_id')
    op.drop_column('organization_identifier', 'type_code')
    op.drop_column('organization_identifier', 'type_display')
    op.drop_column('organization_identifier', 'type_system')
    op.drop_column('organization_identifier', 'type_version')
    op.add_column('organization_telecom', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_telecom', sa.Column('tenant_id', sa.String(), nullable=False))
    op.alter_column('organization_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=True)
    op.alter_column('organization_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_organization_telecom_organization_id'), table_name='organization_telecom')
    op.create_index(op.f('ix_organization_telecom_created_at'), 'organization_telecom', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_telecom_organization_pk'), 'organization_telecom', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_telecom_tenant_id'), 'organization_telecom', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_telecom_updated_at'), 'organization_telecom', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_telecom_organization_id_fkey'), 'organization_telecom', type_='foreignkey')
    op.create_foreign_key(None, 'organization_telecom', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_telecom', 'org_id')
    op.drop_column('organization_telecom', 'organization_id')
    op.add_column('organization_type', sa.Column('organization_pk', sa.BigInteger(), nullable=False))
    op.add_column('organization_type', sa.Column('tenant_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_organization_type_organization_id'), table_name='organization_type')
    op.create_index(op.f('ix_organization_type_created_at'), 'organization_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_type_organization_pk'), 'organization_type', ['organization_pk'], unique=False)
    op.create_index(op.f('ix_organization_type_tenant_id'), 'organization_type', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_type_updated_at'), 'organization_type', ['updated_at'], unique=False)
    op.drop_constraint(op.f('organization_type_organization_id_fkey'), 'organization_type', type_='foreignkey')
    op.create_foreign_key(None, 'organization_type', 'organization', ['organization_pk'], ['id'])
    op.drop_column('organization_type', 'coding_version')
    op.drop_column('organization_type', 'org_id')
    op.drop_column('organization_type', 'organization_id')
    op.drop_column('organization_type', 'coding_user_selected')
    op.drop_column('organization_type', 'coding_display')
    op.drop_column('organization_type', 'coding_system')
    op.drop_column('organization_type', 'coding_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_type', sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_type', sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_type', sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_type', sa.Column('coding_user_selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('organization_type', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_type', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organization_type', sa.Column('coding_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization_type', type_='foreignkey')
    op.create_foreign_key(op.f('organization_type_organization_id_fkey'), 'organization_type', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_type_updated_at'), table_name='organization_type')
    op.drop_index(op.f('ix_organization_type_tenant_id'), table_name='organization_type')
    op.drop_index(op.f('ix_organization_type_organization_pk'), table_name='organization_type')
    op.drop_index(op.f('ix_organization_type_created_at'), table_name='organization_type')
    op.create_index(op.f('ix_organization_type_organization_id'), 'organization_type', ['organization_id'], unique=False)
    op.drop_column('organization_type', 'tenant_id')
    op.drop_column('organization_type', 'organization_pk')
    op.add_column('organization_telecom', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_telecom', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_telecom', type_='foreignkey')
    op.create_foreign_key(op.f('organization_telecom_organization_id_fkey'), 'organization_telecom', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_telecom_updated_at'), table_name='organization_telecom')
    op.drop_index(op.f('ix_organization_telecom_tenant_id'), table_name='organization_telecom')
    op.drop_index(op.f('ix_organization_telecom_organization_pk'), table_name='organization_telecom')
    op.drop_index(op.f('ix_organization_telecom_created_at'), table_name='organization_telecom')
    op.create_index(op.f('ix_organization_telecom_organization_id'), 'organization_telecom', ['organization_id'], unique=False)
    op.alter_column('organization_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False)
    op.drop_column('organization_telecom', 'tenant_id')
    op.drop_column('organization_telecom', 'organization_pk')
    op.add_column('organization_identifier', sa.Column('type_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_identifier', sa.Column('type_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_identifier', sa.Column('type_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_identifier', sa.Column('type_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_identifier', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_identifier', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organization_identifier', sa.Column('type_user_selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization_identifier', type_='foreignkey')
    op.create_foreign_key(op.f('organization_identifier_organization_id_fkey'), 'organization_identifier', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_identifier_updated_at'), table_name='organization_identifier')
    op.drop_index(op.f('ix_organization_identifier_tenant_id'), table_name='organization_identifier')
    op.drop_index(op.f('ix_organization_identifier_organization_pk'), table_name='organization_identifier')
    op.drop_index(op.f('ix_organization_identifier_created_at'), table_name='organization_identifier')
    op.create_unique_constraint(op.f('uq_organization_identifier_system_value'), 'organization_identifier', ['system', 'value'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_organization_identifier_organization_id'), 'organization_identifier', ['organization_id'], unique=False)
    op.alter_column('organization_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('organization_identifier', 'tenant_id')
    op.drop_column('organization_identifier', 'assigner_reference')
    op.drop_column('organization_identifier', 'organization_pk')
    op.add_column('organization_endpoint', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_endpoint', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_endpoint', type_='foreignkey')
    op.create_foreign_key(op.f('organization_endpoint_organization_id_fkey'), 'organization_endpoint', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_endpoint_updated_at'), table_name='organization_endpoint')
    op.drop_index(op.f('ix_organization_endpoint_tenant_id'), table_name='organization_endpoint')
    op.drop_index(op.f('ix_organization_endpoint_organization_pk'), table_name='organization_endpoint')
    op.drop_index(op.f('ix_organization_endpoint_created_at'), table_name='organization_endpoint')
    op.create_unique_constraint(op.f('uq_organization_endpoint_reference'), 'organization_endpoint', ['organization_id', 'reference_type', 'reference_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_organization_endpoint_organization_id'), 'organization_endpoint', ['organization_id'], unique=False)
    op.drop_column('organization_endpoint', 'tenant_id')
    op.drop_column('organization_endpoint', 'reference_reference')
    op.drop_column('organization_endpoint', 'organization_pk')
    op.add_column('organization_contact_telecom', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organization_contact_telecom_updated_at'), table_name='organization_contact_telecom')
    op.drop_index(op.f('ix_organization_contact_telecom_tenant_id'), table_name='organization_contact_telecom')
    op.drop_index(op.f('ix_organization_contact_telecom_created_at'), table_name='organization_contact_telecom')
    op.alter_column('organization_contact_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False)
    op.drop_column('organization_contact_telecom', 'tenant_id')
    op.add_column('organization_contact', sa.Column('purpose_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_contact', sa.Column('purpose_user_selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('organization_contact', sa.Column('purpose_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_contact', sa.Column('purpose_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_contact', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_contact', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organization_contact', sa.Column('purpose_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization_contact', type_='foreignkey')
    op.create_foreign_key(op.f('organization_contact_organization_id_fkey'), 'organization_contact', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_contact_updated_at'), table_name='organization_contact')
    op.drop_index(op.f('ix_organization_contact_tenant_id'), table_name='organization_contact')
    op.drop_index(op.f('ix_organization_contact_organization_pk'), table_name='organization_contact')
    op.drop_index(op.f('ix_organization_contact_created_at'), table_name='organization_contact')
    op.create_index(op.f('ix_organization_contact_organization_id'), 'organization_contact', ['organization_id'], unique=False)
    op.alter_column('organization_contact', 'address_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_line',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organization_contact', 'address_type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type'),
               nullable=False)
    op.alter_column('organization_contact', 'name_suffix',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organization_contact', 'name_prefix',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organization_contact', 'name_given',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('organization_contact', 'tenant_id')
    op.drop_column('organization_contact', 'organization_pk')
    op.add_column('organization_alias', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_alias', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_alias', type_='foreignkey')
    op.create_foreign_key(op.f('organization_alias_organization_id_fkey'), 'organization_alias', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_alias_updated_at'), table_name='organization_alias')
    op.drop_index(op.f('ix_organization_alias_tenant_id'), table_name='organization_alias')
    op.drop_index(op.f('ix_organization_alias_organization_pk'), table_name='organization_alias')
    op.drop_index(op.f('ix_organization_alias_created_at'), table_name='organization_alias')
    op.create_index(op.f('ix_organization_alias_organization_id'), 'organization_alias', ['organization_id'], unique=False)
    op.drop_column('organization_alias', 'tenant_id')
    op.drop_column('organization_alias', 'organization_pk')
    op.add_column('organization_address', sa.Column('organization_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('organization_address', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_address', type_='foreignkey')
    op.create_foreign_key(op.f('organization_address_organization_id_fkey'), 'organization_address', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_organization_address_updated_at'), table_name='organization_address')
    op.drop_index(op.f('ix_organization_address_tenant_id'), table_name='organization_address')
    op.drop_index(op.f('ix_organization_address_organization_pk'), table_name='organization_address')
    op.drop_index(op.f('ix_organization_address_created_at'), table_name='organization_address')
    op.create_index(op.f('ix_organization_address_organization_id'), 'organization_address', ['organization_id'], unique=False)
    op.alter_column('organization_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'line',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organization_address', 'type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type'),
               nullable=False)
    op.drop_column('organization_address', 'tenant_id')
    op.drop_column('organization_address', 'organization_pk')
    op.add_column('organization', sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organization_updated_at'), table_name='organization')
    op.drop_index(op.f('ix_organization_tenant_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.create_index(op.f('ix_organization_org_id'), 'organization', ['org_id'], unique=False)
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('organization', 'tenant_id')
    op.drop_column('organization', 'extension')
    op.drop_column('organization', 'partof_reference')
    op.drop_index(op.f('ix_organization_type_coding_updated_at'), table_name='organization_type_coding')
    op.drop_index(op.f('ix_organization_type_coding_tenant_id'), table_name='organization_type_coding')
    op.drop_index(op.f('ix_organization_type_coding_organization_type_id'), table_name='organization_type_coding')
    op.drop_index(op.f('ix_organization_type_coding_created_at'), table_name='organization_type_coding')
    op.drop_table('organization_type_coding')
    op.drop_index(op.f('ix_organization_identifier_type_coding_updated_at'), table_name='organization_identifier_type_coding')
    op.drop_index(op.f('ix_organization_identifier_type_coding_tenant_id'), table_name='organization_identifier_type_coding')
    op.drop_index(op.f('ix_organization_identifier_type_coding_organization_identifier_id'), table_name='organization_identifier_type_coding')
    op.drop_index(op.f('ix_organization_identifier_type_coding_created_at'), table_name='organization_identifier_type_coding')
    op.drop_table('organization_identifier_type_coding')
    op.drop_index(op.f('ix_organization_contact_purpose_coding_updated_at'), table_name='organization_contact_purpose_coding')
    op.drop_index(op.f('ix_organization_contact_purpose_coding_tenant_id'), table_name='organization_contact_purpose_coding')
    op.drop_index(op.f('ix_organization_contact_purpose_coding_created_at'), table_name='organization_contact_purpose_coding')
    op.drop_index(op.f('ix_organization_contact_purpose_coding_contact_id'), table_name='organization_contact_purpose_coding')
    op.drop_table('organization_contact_purpose_coding')
    # ### end Alembic commands ###
