"""practitioner_role_r4_telecom

Revision ID: 382d7cf7de4b
Revises: 2df49be9fc2b
Create Date: 2026-07-26 15:59:46.706247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '382d7cf7de4b'
down_revision: Union[str, None] = '2df49be9fc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    # PractitionerRole has 3 real rows with practitioner links + availability
    # schedules today, but they predate this R4 restructuring (dual-column
    # practitioner ref, wrapped availability) and the user confirmed it's safe
    # to drop rather than migrate forward.
    op.execute('TRUNCATE TABLE practitioner_role CASCADE')

    op.create_table('practitioner_role_telecom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('system', postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system', create_type=False), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('use', postgresql.ENUM('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use', create_type=False), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_role_telecom_practitioner_role_id'), 'practitioner_role_telecom', ['practitioner_role_id'], unique=False)
    op.drop_index(op.f('ix_practitioner_role_communication_practitioner_role_id'), table_name='practitioner_role_communication')
    op.drop_table('practitioner_role_communication')
    op.drop_index(op.f('ix_practitioner_role_contact_telecom_contact_id'), table_name='practitioner_role_contact_telecom')
    op.drop_table('practitioner_role_contact_telecom')
    op.drop_index(op.f('ix_practitioner_role_contact_name_contact_id'), table_name='practitioner_role_contact_name')
    op.drop_table('practitioner_role_contact_name')
    op.drop_index(op.f('ix_practitioner_role_characteristic_practitioner_role_id'), table_name='practitioner_role_characteristic')
    op.drop_table('practitioner_role_characteristic')
    # contact must drop last — contact_name/contact_telecom FK reference it
    op.drop_index(op.f('ix_practitioner_role_contact_practitioner_role_id'), table_name='practitioner_role_contact')
    op.drop_table('practitioner_role_contact')
    op.add_column('practitioner_role', sa.Column('practitioner_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_practitioner_role_practitioner_fk_id'), table_name='practitioner_role')
    op.create_index(op.f('ix_practitioner_role_practitioner_id'), 'practitioner_role', ['practitioner_id'], unique=False)
    op.drop_constraint(op.f('practitioner_role_practitioner_fk_id_fkey'), 'practitioner_role', type_='foreignkey')
    op.create_foreign_key(None, 'practitioner_role', 'practitioner', ['practitioner_id'], ['id'])
    op.drop_column('practitioner_role', 'practitioner_fk_id')
    op.drop_column('practitioner_role', 'practitioner_ref_id')
    op.add_column('practitioner_role_availability_time', sa.Column('practitioner_role_id', sa.Integer(), nullable=False))
    op.execute("CREATE TYPE day_of_week AS ENUM ('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun')")
    op.alter_column('practitioner_role_availability_time', 'days_of_week',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='day_of_week', create_type=False)),
               existing_nullable=True,
               postgresql_using="string_to_array(days_of_week, ',')::day_of_week[]")
    op.drop_index(op.f('ix_practitioner_role_availability_time_availability_id'), table_name='practitioner_role_availability_time')
    op.create_index(op.f('ix_practitioner_role_availability_time_practitioner_role_id'), 'practitioner_role_availability_time', ['practitioner_role_id'], unique=False)
    op.drop_constraint(op.f('practitioner_role_availability_time_availability_id_fkey'), 'practitioner_role_availability_time', type_='foreignkey')
    op.create_foreign_key(None, 'practitioner_role_availability_time', 'practitioner_role', ['practitioner_role_id'], ['id'])
    op.drop_column('practitioner_role_availability_time', 'availability_id')
    op.add_column('practitioner_role_not_available_time', sa.Column('practitioner_role_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_practitioner_role_not_available_time_availability_id'), table_name='practitioner_role_not_available_time')
    op.create_index(op.f('ix_practitioner_role_not_available_time_practitioner_role_id'), 'practitioner_role_not_available_time', ['practitioner_role_id'], unique=False)
    op.drop_constraint(op.f('practitioner_role_not_available_time_availability_id_fkey'), 'practitioner_role_not_available_time', type_='foreignkey')
    op.create_foreign_key(None, 'practitioner_role_not_available_time', 'practitioner_role', ['practitioner_role_id'], ['id'])
    op.drop_column('practitioner_role_not_available_time', 'availability_id')
    # wrapper table drops last — both children's FK to it were just removed above
    op.drop_index(op.f('ix_practitioner_role_availability_practitioner_role_id'), table_name='practitioner_role_availability')
    op.drop_table('practitioner_role_availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioner_role_not_available_time', sa.Column('availability_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'practitioner_role_not_available_time', type_='foreignkey')
    op.create_foreign_key(op.f('practitioner_role_not_available_time_availability_id_fkey'), 'practitioner_role_not_available_time', 'practitioner_role_availability', ['availability_id'], ['id'])
    op.drop_index(op.f('ix_practitioner_role_not_available_time_practitioner_role_id'), table_name='practitioner_role_not_available_time')
    op.create_index(op.f('ix_practitioner_role_not_available_time_availability_id'), 'practitioner_role_not_available_time', ['availability_id'], unique=False)
    op.drop_column('practitioner_role_not_available_time', 'practitioner_role_id')
    op.add_column('practitioner_role_availability_time', sa.Column('availability_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'practitioner_role_availability_time', type_='foreignkey')
    op.create_foreign_key(op.f('practitioner_role_availability_time_availability_id_fkey'), 'practitioner_role_availability_time', 'practitioner_role_availability', ['availability_id'], ['id'])
    op.drop_index(op.f('ix_practitioner_role_availability_time_practitioner_role_id'), table_name='practitioner_role_availability_time')
    op.create_index(op.f('ix_practitioner_role_availability_time_availability_id'), 'practitioner_role_availability_time', ['availability_id'], unique=False)
    op.alter_column('practitioner_role_availability_time', 'days_of_week',
               existing_type=postgresql.ARRAY(postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='day_of_week', create_type=False)),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using="array_to_string(days_of_week, ',')")
    op.execute('DROP TYPE day_of_week')
    op.drop_column('practitioner_role_availability_time', 'practitioner_role_id')
    op.add_column('practitioner_role', sa.Column('practitioner_ref_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('practitioner_role', sa.Column('practitioner_fk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'practitioner_role', type_='foreignkey')
    op.create_foreign_key(op.f('practitioner_role_practitioner_fk_id_fkey'), 'practitioner_role', 'practitioner', ['practitioner_fk_id'], ['id'])
    op.drop_index(op.f('ix_practitioner_role_practitioner_id'), table_name='practitioner_role')
    op.create_index(op.f('ix_practitioner_role_practitioner_fk_id'), 'practitioner_role', ['practitioner_fk_id'], unique=False)
    op.drop_column('practitioner_role', 'practitioner_id')
    op.create_table('practitioner_role_characteristic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], name=op.f('practitioner_role_characteristic_practitioner_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_characteristic_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_characteristic_practitioner_role_id'), 'practitioner_role_characteristic', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_contact_name',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('use', postgresql.ENUM('usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden', name='human_name_use', create_type=False), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('family', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('given', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suffix', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['practitioner_role_contact.id'], name=op.f('practitioner_role_contact_name_contact_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_contact_name_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_contact_name_contact_id'), 'practitioner_role_contact_name', ['contact_id'], unique=False)
    op.create_table('practitioner_role_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], name=op.f('practitioner_role_availability_practitioner_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_availability_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_availability_practitioner_role_id'), 'practitioner_role_availability', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_contact_telecom',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system', postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system', create_type=False), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('use', postgresql.ENUM('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use', create_type=False), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['practitioner_role_contact.id'], name=op.f('practitioner_role_contact_telecom_contact_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_contact_telecom_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_contact_telecom_contact_id'), 'practitioner_role_contact_telecom', ['contact_id'], unique=False)
    op.create_table('practitioner_role_communication',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], name=op.f('practitioner_role_communication_practitioner_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_communication_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_communication_practitioner_role_id'), 'practitioner_role_communication', ['practitioner_role_id'], unique=False)
    op.create_table('practitioner_role_contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practitioner_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_use', postgresql.ENUM('home', 'work', 'temp', 'old', 'billing', name='address_use', create_type=False), autoincrement=False, nullable=True),
    sa.Column('address_type', postgresql.ENUM('postal', 'physical', 'both', name='address_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('address_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('address_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('organization_type', postgresql.ENUM('Organization', name='organization_reference_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practitioner_role_id'], ['practitioner_role.id'], name=op.f('practitioner_role_contact_practitioner_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practitioner_role_contact_pkey'))
    )
    op.create_index(op.f('ix_practitioner_role_contact_practitioner_role_id'), 'practitioner_role_contact', ['practitioner_role_id'], unique=False)
    op.drop_index(op.f('ix_practitioner_role_telecom_practitioner_role_id'), table_name='practitioner_role_telecom')
    op.drop_table('practitioner_role_telecom')
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
