"""add_insurance_plan

Revision ID: 4bd3cf74b229
Revises: f76667f63638
Create Date: 2026-06-09 09:31:37.135147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd3cf74b229'
down_revision: Union[str, None] = 'f76667f63638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    op.create_table('insurance_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), server_default=sa.text("nextval('insurance_plan_pub_seq')"), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', 'unknown', name='insurance_plan_status'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owned_by_id', sa.Integer(), nullable=True),
    sa.Column('owned_by_display', sa.String(), nullable=True),
    sa.Column('administered_by_id', sa.Integer(), nullable=True),
    sa.Column('administered_by_display', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_id'), 'insurance_plan', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_plan_insurance_plan_id'), 'insurance_plan', ['insurance_plan_id'], unique=True)
    op.create_index(op.f('ix_insurance_plan_org_id'), 'insurance_plan', ['org_id'], unique=False)
    op.create_index(op.f('ix_insurance_plan_user_id'), 'insurance_plan', ['user_id'], unique=False)
    op.create_table('insurance_plan_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_alias_insurance_plan_id'), 'insurance_plan_alias', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('purpose_system', sa.String(), nullable=True),
    sa.Column('purpose_code', sa.String(), nullable=True),
    sa.Column('purpose_display', sa.String(), nullable=True),
    sa.Column('purpose_text', sa.String(), nullable=True),
    sa.Column('name_use', sa.String(), nullable=True),
    sa.Column('name_text', sa.String(), nullable=True),
    sa.Column('name_family', sa.String(), nullable=True),
    sa.Column('name_given', sa.String(), nullable=True),
    sa.Column('name_prefix', sa.String(), nullable=True),
    sa.Column('name_suffix', sa.String(), nullable=True),
    sa.Column('address_use', sa.String(), nullable=True),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('address_text', sa.String(), nullable=True),
    sa.Column('address_line', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_district', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('address_postal_code', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_contact_insurance_plan_id'), 'insurance_plan_contact', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_coverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_coverage_insurance_plan_id'), 'insurance_plan_coverage', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_coverage_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_coverage_area_insurance_plan_id'), 'insurance_plan_coverage_area', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_endpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_endpoint_insurance_plan_id'), 'insurance_plan_endpoint', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_identifier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_identifier_insurance_plan_id'), 'insurance_plan_identifier', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_network_insurance_plan_id'), 'insurance_plan_network', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_insurance_plan_id'), 'insurance_plan_plan', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_type_insurance_plan_id'), 'insurance_plan_type', ['insurance_plan_id'], unique=False)
    op.create_table('insurance_plan_contact_telecom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['insurance_plan_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_contact_telecom_contact_id'), 'insurance_plan_contact_telecom', ['contact_id'], unique=False)
    op.create_table('insurance_plan_coverage_benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coverage_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('requirement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['insurance_plan_coverage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_coverage_benefit_coverage_id'), 'insurance_plan_coverage_benefit', ['coverage_id'], unique=False)
    op.create_table('insurance_plan_coverage_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coverage_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['insurance_plan_coverage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_coverage_network_coverage_id'), 'insurance_plan_coverage_network', ['coverage_id'], unique=False)
    op.create_table('insurance_plan_plan_coverage_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plan_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_coverage_area_plan_id'), 'insurance_plan_plan_coverage_area', ['plan_id'], unique=False)
    op.create_table('insurance_plan_plan_general_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('cost_value', sa.Numeric(), nullable=True),
    sa.Column('cost_currency', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plan_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_general_cost_plan_id'), 'insurance_plan_plan_general_cost', ['plan_id'], unique=False)
    op.create_table('insurance_plan_plan_identifier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('use', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plan_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_identifier_plan_id'), 'insurance_plan_plan_identifier', ['plan_id'], unique=False)
    op.create_table('insurance_plan_plan_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plan_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_network_plan_id'), 'insurance_plan_plan_network', ['plan_id'], unique=False)
    op.create_table('insurance_plan_plan_specific_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('category_system', sa.String(), nullable=True),
    sa.Column('category_code', sa.String(), nullable=True),
    sa.Column('category_display', sa.String(), nullable=True),
    sa.Column('category_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plan_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_specific_cost_plan_id'), 'insurance_plan_plan_specific_cost', ['plan_id'], unique=False)
    op.create_table('insurance_plan_coverage_benefit_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('value_value', sa.Numeric(), nullable=True),
    sa.Column('value_comparator', sa.String(), nullable=True),
    sa.Column('value_unit', sa.String(), nullable=True),
    sa.Column('value_system', sa.String(), nullable=True),
    sa.Column('value_code', sa.String(), nullable=True),
    sa.Column('code_system', sa.String(), nullable=True),
    sa.Column('code_code', sa.String(), nullable=True),
    sa.Column('code_display', sa.String(), nullable=True),
    sa.Column('code_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['benefit_id'], ['insurance_plan_coverage_benefit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_coverage_benefit_limit_benefit_id'), 'insurance_plan_coverage_benefit_limit', ['benefit_id'], unique=False)
    op.create_table('insurance_plan_plan_sc_benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specific_cost_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['specific_cost_id'], ['insurance_plan_plan_specific_cost.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_sc_benefit_specific_cost_id'), 'insurance_plan_plan_sc_benefit', ['specific_cost_id'], unique=False)
    op.create_table('insurance_plan_plan_sc_benefit_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sc_benefit_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('type_system', sa.String(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_display', sa.String(), nullable=True),
    sa.Column('type_text', sa.String(), nullable=True),
    sa.Column('applicability_system', sa.String(), nullable=True),
    sa.Column('applicability_code', sa.String(), nullable=True),
    sa.Column('applicability_display', sa.String(), nullable=True),
    sa.Column('applicability_text', sa.String(), nullable=True),
    sa.Column('qualifiers_json', sa.Text(), nullable=True),
    sa.Column('value_value', sa.Numeric(), nullable=True),
    sa.Column('value_comparator', sa.String(), nullable=True),
    sa.Column('value_unit', sa.String(), nullable=True),
    sa.Column('value_system', sa.String(), nullable=True),
    sa.Column('value_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sc_benefit_id'], ['insurance_plan_plan_sc_benefit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plan_plan_sc_benefit_cost_sc_benefit_id'), 'insurance_plan_plan_sc_benefit_cost', ['sc_benefit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_plan_plan_sc_benefit_cost_sc_benefit_id'), table_name='insurance_plan_plan_sc_benefit_cost')
    op.drop_table('insurance_plan_plan_sc_benefit_cost')
    op.drop_index(op.f('ix_insurance_plan_plan_sc_benefit_specific_cost_id'), table_name='insurance_plan_plan_sc_benefit')
    op.drop_table('insurance_plan_plan_sc_benefit')
    op.drop_index(op.f('ix_insurance_plan_coverage_benefit_limit_benefit_id'), table_name='insurance_plan_coverage_benefit_limit')
    op.drop_table('insurance_plan_coverage_benefit_limit')
    op.drop_index(op.f('ix_insurance_plan_plan_specific_cost_plan_id'), table_name='insurance_plan_plan_specific_cost')
    op.drop_table('insurance_plan_plan_specific_cost')
    op.drop_index(op.f('ix_insurance_plan_plan_network_plan_id'), table_name='insurance_plan_plan_network')
    op.drop_table('insurance_plan_plan_network')
    op.drop_index(op.f('ix_insurance_plan_plan_identifier_plan_id'), table_name='insurance_plan_plan_identifier')
    op.drop_table('insurance_plan_plan_identifier')
    op.drop_index(op.f('ix_insurance_plan_plan_general_cost_plan_id'), table_name='insurance_plan_plan_general_cost')
    op.drop_table('insurance_plan_plan_general_cost')
    op.drop_index(op.f('ix_insurance_plan_plan_coverage_area_plan_id'), table_name='insurance_plan_plan_coverage_area')
    op.drop_table('insurance_plan_plan_coverage_area')
    op.drop_index(op.f('ix_insurance_plan_coverage_network_coverage_id'), table_name='insurance_plan_coverage_network')
    op.drop_table('insurance_plan_coverage_network')
    op.drop_index(op.f('ix_insurance_plan_coverage_benefit_coverage_id'), table_name='insurance_plan_coverage_benefit')
    op.drop_table('insurance_plan_coverage_benefit')
    op.drop_index(op.f('ix_insurance_plan_contact_telecom_contact_id'), table_name='insurance_plan_contact_telecom')
    op.drop_table('insurance_plan_contact_telecom')
    op.drop_index(op.f('ix_insurance_plan_type_insurance_plan_id'), table_name='insurance_plan_type')
    op.drop_table('insurance_plan_type')
    op.drop_index(op.f('ix_insurance_plan_plan_insurance_plan_id'), table_name='insurance_plan_plan')
    op.drop_table('insurance_plan_plan')
    op.drop_index(op.f('ix_insurance_plan_network_insurance_plan_id'), table_name='insurance_plan_network')
    op.drop_table('insurance_plan_network')
    op.drop_index(op.f('ix_insurance_plan_identifier_insurance_plan_id'), table_name='insurance_plan_identifier')
    op.drop_table('insurance_plan_identifier')
    op.drop_index(op.f('ix_insurance_plan_endpoint_insurance_plan_id'), table_name='insurance_plan_endpoint')
    op.drop_table('insurance_plan_endpoint')
    op.drop_index(op.f('ix_insurance_plan_coverage_area_insurance_plan_id'), table_name='insurance_plan_coverage_area')
    op.drop_table('insurance_plan_coverage_area')
    op.drop_index(op.f('ix_insurance_plan_coverage_insurance_plan_id'), table_name='insurance_plan_coverage')
    op.drop_table('insurance_plan_coverage')
    op.drop_index(op.f('ix_insurance_plan_contact_insurance_plan_id'), table_name='insurance_plan_contact')
    op.drop_table('insurance_plan_contact')
    op.drop_index(op.f('ix_insurance_plan_alias_insurance_plan_id'), table_name='insurance_plan_alias')
    op.drop_table('insurance_plan_alias')
    op.drop_index(op.f('ix_insurance_plan_user_id'), table_name='insurance_plan')
    op.drop_index(op.f('ix_insurance_plan_org_id'), table_name='insurance_plan')
    op.drop_index(op.f('ix_insurance_plan_insurance_plan_id'), table_name='insurance_plan')
    op.drop_index(op.f('ix_insurance_plan_id'), table_name='insurance_plan')
    op.drop_table('insurance_plan')
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
