"""organization_endpoint identifier fallback and unique constraint

Revision ID: 936898518be3
Revises: f65cde43f38e
Create Date: 2026-08-01 15:12:09.645687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936898518be3'
down_revision: Union[str, None] = 'f65cde43f38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    op.alter_column('organization', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('organization_endpoint', sa.Column('reference_identifier_use', sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_endpoint', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_organization_endpoint_reference', 'organization_endpoint', ['organization_id', 'reference_type', 'reference_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organization_endpoint_reference', 'organization_endpoint', type_='unique')
    op.drop_column('organization_endpoint', 'reference_identifier_period_end')
    op.drop_column('organization_endpoint', 'reference_identifier_period_start')
    op.drop_column('organization_endpoint', 'reference_identifier_value')
    op.drop_column('organization_endpoint', 'reference_identifier_system')
    op.drop_column('organization_endpoint', 'reference_identifier_type_user_selected')
    op.drop_column('organization_endpoint', 'reference_identifier_type_text')
    op.drop_column('organization_endpoint', 'reference_identifier_type_display')
    op.drop_column('organization_endpoint', 'reference_identifier_type_code')
    op.drop_column('organization_endpoint', 'reference_identifier_type_version')
    op.drop_column('organization_endpoint', 'reference_identifier_type_system')
    op.drop_column('organization_endpoint', 'reference_identifier_use')
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
