"""location model rewrite and bigint ids across sub-resources

Revision ID: ad5a4b97064d
Revises: e3a0e1ed27f8
Create Date: 2026-08-08 15:13:04.867592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5a4b97064d'
down_revision: Union[str, None] = 'e3a0e1ed27f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    op.add_column('location', sa.Column('operational_status_version', sa.String(), nullable=True))
    op.add_column('location', sa.Column('operational_status_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('physical_type_version', sa.String(), nullable=True))
    op.add_column('location', sa.Column('physical_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_type_system', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_type_version', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_type_code', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_type_display', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_type_text', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_system', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_value', sa.String(), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location', sa.Column('managing_organization_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_type_system', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_type_version', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_type_code', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_type_display', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_type_text', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_system', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_value', sa.String(), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location', sa.Column('part_of_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('location', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('location_pub_seq'::regclass)"))
    op.alter_column('location', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'status',
               existing_type=postgresql.ENUM('active', 'suspended', 'inactive', name='location_status'),
               nullable=False)
    op.alter_column('location', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'mode',
               existing_type=postgresql.ENUM('instance', 'kind', name='location_mode'),
               nullable=False)
    op.alter_column('location', 'address_use',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('home', 'work', 'temp', 'old', 'billing', name='address_use', create_type=False),
               existing_nullable=True,
               postgresql_using='address_use::text::address_use')
    op.alter_column('location', 'address_type',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('postal', 'physical', 'both', name='address_type', create_type=False),
               nullable=False,
               postgresql_using='address_type::text::address_type')
    op.alter_column('location', 'address_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'address_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'address_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location', 'managing_organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('location', 'part_of_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('location', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_location_managing_organization_id'), table_name='location')
    op.drop_index(op.f('ix_location_part_of_id'), table_name='location')
    op.drop_index(op.f('ix_location_user_id'), table_name='location')
    op.drop_constraint(op.f('location_managing_organization_id_fkey'), 'location', type_='foreignkey')
    op.drop_constraint(op.f('location_part_of_id_fkey'), 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    op.add_column('location_alias', sa.Column('value', sa.String(), nullable=False))
    op.add_column('location_alias', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location_alias', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_alias', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('location_alias', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('location_alias', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_alias', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('location_alias', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('location_alias', 'alias')
    op.add_column('location_endpoint', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_endpoint', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_endpoint', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location_endpoint', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_endpoint', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('location_endpoint', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('location_endpoint', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_endpoint', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('location_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location_endpoint', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_unique_constraint('uq_location_endpoint_reference', 'location_endpoint', ['location_id', 'reference_type', 'reference_id'])
    op.add_column('location_hours_of_operation', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location_hours_of_operation', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_hours_of_operation', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('location_hours_of_operation', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('location_hours_of_operation', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_hours_of_operation', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('location_hours_of_operation', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location_hours_of_operation', 'opening_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using='opening_time::time')
    op.alter_column('location_hours_of_operation', 'closing_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using='closing_time::time')
    op.add_column('location_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_type', postgresql.ENUM('Organization', name='organization_reference_type', create_type=False), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_id', sa.BigInteger(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('location_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('location_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_identifier', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('location_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location_identifier', 'use',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False),
               existing_nullable=True,
               postgresql_using='"use"::text::identifier_use')
    op.alter_column('location_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_location_identifier_system_value', 'location_identifier', ['system', 'value'])
    op.drop_column('location_identifier', 'assigner')
    op.add_column('location_telecom', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location_telecom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_telecom', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('location_telecom', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('location_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_telecom', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('location_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('location_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False)
    op.alter_column('location_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('location_type', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('location_type', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('location_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('location_type', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('location_type', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('location_type', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('location_type', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('location_type', 'location_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('location_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization', 'partof_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('organization_address', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_alias', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_contact', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_contact_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_contact_telecom', 'contact_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('organization_endpoint', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_endpoint', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('organization_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_identifier', 'assigner_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('organization_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_type', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient', 'managing_organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('patient_address', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_communication', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('patient_contact_relationship', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact_relationship', 'contact_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('patient_contact_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact_telecom', 'contact_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('patient_general_practitioner', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_general_practitioner', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('patient_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_identifier', 'assigner_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('patient_link', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_link', 'other_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('patient_name', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_photo', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_address', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_communication', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_identifier', 'assigner_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('practitioner_name', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_photo', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_qualification', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_qualification', 'issuer_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('practitioner_qualification_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_qualification_identifier', 'qualification_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('practitioner_qualification_identifier', 'assigner_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('practitioner_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practitioner_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_qualification_identifier', 'assigner_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('practitioner_qualification_identifier', 'qualification_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('practitioner_qualification_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_qualification', 'issuer_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('practitioner_qualification', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_photo', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_name', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_identifier', 'assigner_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('practitioner_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_communication', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('practitioner_address', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_photo', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_name', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_link', 'other_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('patient_link', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_identifier', 'assigner_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('patient_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_general_practitioner', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('patient_general_practitioner', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact_telecom', 'contact_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('patient_contact_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact_relationship', 'contact_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('patient_contact_relationship', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_contact', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('patient_contact', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_communication', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient_address', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('patient', 'managing_organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('organization_type', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_identifier', 'assigner_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('organization_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_endpoint', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('organization_endpoint', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_contact_telecom', 'contact_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization_contact_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_contact', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_alias', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_address', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization', 'partof_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('location_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_type', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_type', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location_type', 'updated_by')
    op.drop_column('location_type', 'created_by')
    op.drop_column('location_type', 'updated_at')
    op.drop_column('location_type', 'created_at')
    op.drop_column('location_type', 'coding_user_selected')
    op.drop_column('location_type', 'coding_version')
    op.alter_column('location_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=True)
    op.alter_column('location_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_telecom', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location_telecom', 'updated_by')
    op.drop_column('location_telecom', 'created_by')
    op.drop_column('location_telecom', 'updated_at')
    op.drop_column('location_telecom', 'created_at')
    op.add_column('location_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_location_identifier_system_value', 'location_identifier', type_='unique')
    op.alter_column('location_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_identifier', 'use',
               existing_type=postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='"use"::text')
    op.alter_column('location_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_identifier', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location_identifier', 'updated_by')
    op.drop_column('location_identifier', 'created_by')
    op.drop_column('location_identifier', 'updated_at')
    op.drop_column('location_identifier', 'created_at')
    op.drop_column('location_identifier', 'assigner_identifier_period_end')
    op.drop_column('location_identifier', 'assigner_identifier_period_start')
    op.drop_column('location_identifier', 'assigner_identifier_value')
    op.drop_column('location_identifier', 'assigner_identifier_system')
    op.drop_column('location_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('location_identifier', 'assigner_identifier_type_text')
    op.drop_column('location_identifier', 'assigner_identifier_type_display')
    op.drop_column('location_identifier', 'assigner_identifier_type_code')
    op.drop_column('location_identifier', 'assigner_identifier_type_version')
    op.drop_column('location_identifier', 'assigner_identifier_type_system')
    op.drop_column('location_identifier', 'assigner_identifier_use')
    op.drop_column('location_identifier', 'assigner_display')
    op.drop_column('location_identifier', 'assigner_id')
    op.drop_column('location_identifier', 'assigner_type')
    op.drop_column('location_identifier', 'type_user_selected')
    op.drop_column('location_identifier', 'type_version')
    op.alter_column('location_hours_of_operation', 'closing_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='closing_time::text')
    op.alter_column('location_hours_of_operation', 'opening_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='opening_time::text')
    op.alter_column('location_hours_of_operation', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_hours_of_operation', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_hours_of_operation', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location_hours_of_operation', 'updated_by')
    op.drop_column('location_hours_of_operation', 'created_by')
    op.drop_column('location_hours_of_operation', 'updated_at')
    op.drop_column('location_hours_of_operation', 'created_at')
    op.drop_constraint('uq_location_endpoint_reference', 'location_endpoint', type_='unique')
    op.alter_column('location_endpoint', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('location_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_endpoint', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_endpoint', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location_endpoint', 'updated_by')
    op.drop_column('location_endpoint', 'created_by')
    op.drop_column('location_endpoint', 'updated_at')
    op.drop_column('location_endpoint', 'created_at')
    op.drop_column('location_endpoint', 'reference_identifier_period_end')
    op.drop_column('location_endpoint', 'reference_identifier_period_start')
    op.drop_column('location_endpoint', 'reference_identifier_value')
    op.drop_column('location_endpoint', 'reference_identifier_system')
    op.drop_column('location_endpoint', 'reference_identifier_type_user_selected')
    op.drop_column('location_endpoint', 'reference_identifier_type_text')
    op.drop_column('location_endpoint', 'reference_identifier_type_display')
    op.drop_column('location_endpoint', 'reference_identifier_type_code')
    op.drop_column('location_endpoint', 'reference_identifier_type_version')
    op.drop_column('location_endpoint', 'reference_identifier_type_system')
    op.drop_column('location_endpoint', 'reference_identifier_use')
    op.add_column('location_alias', sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('location_alias', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location_alias', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_alias', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location_alias', 'updated_by')
    op.drop_column('location_alias', 'created_by')
    op.drop_column('location_alias', 'updated_at')
    op.drop_column('location_alias', 'created_at')
    op.drop_column('location_alias', 'value')
    op.add_column('location', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('location_part_of_id_fkey'), 'location', 'location', ['part_of_id'], ['id'])
    op.create_foreign_key(op.f('location_managing_organization_id_fkey'), 'location', 'organization', ['managing_organization_id'], ['id'])
    op.create_index(op.f('ix_location_user_id'), 'location', ['user_id'], unique=False)
    op.create_index(op.f('ix_location_part_of_id'), 'location', ['part_of_id'], unique=False)
    op.create_index(op.f('ix_location_managing_organization_id'), 'location', ['managing_organization_id'], unique=False)
    op.alter_column('location', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'part_of_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('location', 'managing_organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('location', 'address_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'address_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'address_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'address_type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type', create_type=False),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='address_type::text')
    op.alter_column('location', 'address_use',
               existing_type=postgresql.ENUM('home', 'work', 'temp', 'old', 'billing', name='address_use', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='address_use::text')
    op.alter_column('location', 'mode',
               existing_type=postgresql.ENUM('instance', 'kind', name='location_mode'),
               nullable=True)
    op.alter_column('location', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'status',
               existing_type=postgresql.ENUM('active', 'suspended', 'inactive', name='location_status'),
               nullable=True)
    op.alter_column('location', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('location', 'location_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('location_pub_seq'::regclass)"))
    op.alter_column('location', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('location', 'part_of_identifier_period_end')
    op.drop_column('location', 'part_of_identifier_period_start')
    op.drop_column('location', 'part_of_identifier_value')
    op.drop_column('location', 'part_of_identifier_system')
    op.drop_column('location', 'part_of_identifier_type_user_selected')
    op.drop_column('location', 'part_of_identifier_type_text')
    op.drop_column('location', 'part_of_identifier_type_display')
    op.drop_column('location', 'part_of_identifier_type_code')
    op.drop_column('location', 'part_of_identifier_type_version')
    op.drop_column('location', 'part_of_identifier_type_system')
    op.drop_column('location', 'part_of_identifier_use')
    op.drop_column('location', 'managing_organization_identifier_period_end')
    op.drop_column('location', 'managing_organization_identifier_period_start')
    op.drop_column('location', 'managing_organization_identifier_value')
    op.drop_column('location', 'managing_organization_identifier_system')
    op.drop_column('location', 'managing_organization_identifier_type_user_selected')
    op.drop_column('location', 'managing_organization_identifier_type_text')
    op.drop_column('location', 'managing_organization_identifier_type_display')
    op.drop_column('location', 'managing_organization_identifier_type_code')
    op.drop_column('location', 'managing_organization_identifier_type_version')
    op.drop_column('location', 'managing_organization_identifier_type_system')
    op.drop_column('location', 'managing_organization_identifier_use')
    op.drop_column('location', 'physical_type_user_selected')
    op.drop_column('location', 'physical_type_version')
    op.drop_column('location', 'operational_status_user_selected')
    op.drop_column('location', 'operational_status_version')
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
