"""fhir_profile_table

Revision ID: b63b799d606f
Revises: 275311fe9686
Create Date: 2026-10-07 19:23:16.435838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b63b799d606f'
down_revision: Union[str, None] = '275311fe9686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed ~34 `CREATE SEQUENCE IF NOT EXISTS`
    # statements here for every other resource's _pub_seq. Same false
    # positive documented in migrations/versions/275311fe9686_organization_rework.py
    # — every one of those sequences already exists in the live DB; Alembic
    # just doesn't reliably track standalone `Sequence` objects against what's
    # already reflected there. Removed to keep this migration scoped to the
    # actual new table.
    op.create_table('fhir_profile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('scope_level', sa.Enum('base', 'country', 'organization', name='fhir_profile_scope_level'), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=True),
    sa.Column('parent_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('version', sa.String(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', 'unknown', name='fhir_profile_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('structure_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_profile_id'], ['fhir_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url', 'version', name='uq_fhir_profile_url_version')
    )
    op.create_index('ix_fhir_profile_resource_type', 'fhir_profile', ['resource_type'], unique=False)
    op.create_index('ix_fhir_profile_scope_id', 'fhir_profile', ['scope_id'], unique=False)
    op.create_index('ix_fhir_profile_scope_level', 'fhir_profile', ['scope_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fhir_profile_scope_level', table_name='fhir_profile')
    op.drop_index('ix_fhir_profile_scope_id', table_name='fhir_profile')
    op.drop_index('ix_fhir_profile_resource_type', table_name='fhir_profile')
    op.drop_table('fhir_profile')
    # ### end Alembic commands ###
