"""appointment_r4_rewrite

Revision ID: b9af7ac9b9ce
Revises: d6c9ce92f33f
Create Date: 2026-07-26 15:38:44.534895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9af7ac9b9ce'
down_revision: Union[str, None] = 'd6c9ce92f33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    # Drop old appointment_reason (owns appointment_reason_reference_type with 5
    # values incl. DiagnosticReport) BEFORE creating the new split tables, so the
    # replacement appointment_reason_reference table can freshly create the type
    # with the narrowed R4 4-value set instead of reusing the stale 5-value one.
    op.drop_index(op.f('ix_appointment_reason_appointment_id'), table_name='appointment_reason')
    op.drop_table('appointment_reason')
    op.execute('DROP TYPE appointment_reason_reference_type')

    op.create_table('appointment_reason_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_reason_code_appointment_id'), 'appointment_reason_code', ['appointment_id'], unique=False)
    op.create_table('appointment_reason_reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('Condition', 'Procedure', 'Observation', 'ImmunizationRecommendation', name='appointment_reason_reference_type'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_reason_reference_appointment_id'), 'appointment_reason_reference', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_appointment_patient_instruction_appointment_id'), table_name='appointment_patient_instruction')
    op.drop_table('appointment_patient_instruction')
    op.execute('DROP TYPE appointment_pi_reference_type')
    op.drop_index(op.f('ix_appointment_replaces_appointment_id'), table_name='appointment_replaces')
    op.drop_table('appointment_replaces')
    op.execute('DROP TYPE appointment_replaces_reference_type')
    op.drop_index(op.f('ix_appointment_note_appointment_id'), table_name='appointment_note')
    op.drop_table('appointment_note')
    op.execute('DROP TYPE appointment_note_author_reference_type')
    op.drop_index(op.f('ix_appointment_virtual_service_appointment_id'), table_name='appointment_virtual_service')
    op.drop_table('appointment_virtual_service')
    op.drop_index(op.f('ix_appointment_account_appointment_id'), table_name='appointment_account')
    op.drop_table('appointment_account')
    op.execute('DROP TYPE appointment_account_reference_type')
    op.drop_index(op.f('ix_appointment_class_appointment_id'), table_name='appointment_class')
    op.drop_table('appointment_class')
    op.add_column('appointment', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('appointment', sa.Column('patient_instruction', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_appointment_encounter_id'), table_name='appointment')
    op.drop_constraint(op.f('appointment_encounter_id_fkey'), 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'encounter_id')
    op.drop_column('appointment', 'encounter_type')
    op.drop_column('appointment', 'previous_appointment_display')
    op.drop_column('appointment', 'originating_appointment_display')
    op.drop_column('appointment', 'priority_code')
    op.drop_column('appointment', 'priority_system')
    op.drop_column('appointment', 'cancellation_date')
    op.drop_column('appointment', 'encounter_display')
    op.drop_column('appointment', 'originating_appointment_id')
    op.drop_column('appointment', 'previous_appointment_id')
    op.drop_column('appointment', 'subject_display')
    op.drop_column('appointment', 'subject_id')
    op.drop_column('appointment', 'occurrence_changed')
    op.drop_column('appointment', 'priority_text')
    op.drop_column('appointment', 'priority_display')
    op.drop_column('appointment', 'subject_type')
    op.drop_column('appointment', 'recurrence_id')
    # required: BOOLEAN -> code enum has no sane value mapping (true/false isn't
    # required/optional/information-only) — table is empty in dev, so drop to NULL.
    op.execute(
        "CREATE TYPE appointment_participant_required AS ENUM "
        "('required', 'optional', 'information_only')"
    )
    op.execute(
        "ALTER TABLE appointment_participant ADD COLUMN required_new "
        "appointment_participant_required"
    )
    op.execute('ALTER TABLE appointment_participant DROP COLUMN required')
    op.execute('ALTER TABLE appointment_participant RENAME COLUMN required_new TO required')
    op.execute(
        "CREATE TYPE appointment_participant_status AS ENUM "
        "('accepted', 'declined', 'tentative', 'needs_action')"
    )
    op.alter_column('appointment_participant', 'status',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('accepted', 'declined', 'tentative', 'needs_action', name='appointment_participant_status', create_type=False),
               existing_nullable=False,
               postgresql_using='status::text::appointment_participant_status')
    op.drop_column('appointment_service_type', 'reference_display')
    op.drop_column('appointment_service_type', 'reference_id')
    op.drop_column('appointment_service_type', 'reference_type')
    op.execute('DROP TYPE appointment_service_type_reference_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE appointment_service_type_reference_type AS ENUM ('HealthcareService')")
    op.add_column('appointment_service_type', sa.Column('reference_type', postgresql.ENUM('HealthcareService', name='appointment_service_type_reference_type', create_type=False), autoincrement=False, nullable=True))
    op.add_column('appointment_service_type', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment_service_type', sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('appointment_participant', 'status',
               existing_type=postgresql.ENUM('accepted', 'declined', 'tentative', 'needs_action', name='appointment_participant_status', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='status::text')
    op.execute('DROP TYPE appointment_participant_status')
    # required: code enum -> boolean has no sane value mapping, same as upgrade — drop to NULL.
    op.execute('ALTER TABLE appointment_participant ADD COLUMN required_old BOOLEAN')
    op.execute('ALTER TABLE appointment_participant DROP COLUMN required')
    op.execute('ALTER TABLE appointment_participant RENAME COLUMN required_old TO required')
    op.execute('DROP TYPE appointment_participant_required')
    op.add_column('appointment', sa.Column('recurrence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('subject_type', postgresql.ENUM('Patient', 'Group', name='subject_reference_type'), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('priority_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('priority_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('occurrence_changed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('subject_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('previous_appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('originating_appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('encounter_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('cancellation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('priority_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('priority_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('originating_appointment_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('previous_appointment_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('encounter_type', postgresql.ENUM('Encounter', name='encounter_reference_type'), autoincrement=False, nullable=True))
    op.add_column('appointment', sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointment_encounter_id_fkey'), 'appointment', 'encounter', ['encounter_id'], ['id'])
    op.create_index(op.f('ix_appointment_encounter_id'), 'appointment', ['encounter_id'], unique=False)
    op.drop_column('appointment', 'patient_instruction')
    op.drop_column('appointment', 'comment')
    op.drop_column('appointment', 'priority')
    op.create_table('appointment_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_class_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_class_pkey'))
    )
    op.create_index(op.f('ix_appointment_class_appointment_id'), 'appointment_class', ['appointment_id'], unique=False)
    op.create_table('appointment_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('Account', name='appointment_account_reference_type'), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_account_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_account_pkey'))
    )
    op.create_index(op.f('ix_appointment_account_appointment_id'), 'appointment_account', ['appointment_id'], unique=False)
    op.create_table('appointment_virtual_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_virtual_service_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_virtual_service_pkey'))
    )
    op.create_index(op.f('ix_appointment_virtual_service_appointment_id'), 'appointment_virtual_service', ['appointment_id'], unique=False)
    op.create_table('appointment_note',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_string', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_reference_type', postgresql.ENUM('Practitioner', 'PractitionerRole', 'Patient', 'RelatedPerson', 'Organization', name='appointment_note_author_reference_type'), autoincrement=False, nullable=True),
    sa.Column('author_reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_note_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_note_pkey'))
    )
    op.create_index(op.f('ix_appointment_note_appointment_id'), 'appointment_note', ['appointment_id'], unique=False)
    op.create_table('appointment_replaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('Appointment', name='appointment_replaces_reference_type'), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_replaces_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_replaces_pkey'))
    )
    op.create_index(op.f('ix_appointment_replaces_appointment_id'), 'appointment_replaces', ['appointment_id'], unique=False)
    op.create_table('appointment_patient_instruction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('DocumentReference', 'Binary', 'Communication', name='appointment_pi_reference_type'), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_patient_instruction_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_patient_instruction_pkey'))
    )
    op.create_index(op.f('ix_appointment_patient_instruction_appointment_id'), 'appointment_patient_instruction', ['appointment_id'], unique=False)
    op.create_table('appointment_reason',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('Condition', 'Procedure', 'Observation', 'ImmunizationRecommendation', 'DiagnosticReport', name='appointment_reason_reference_type'), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('appointment_reason_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_reason_pkey'))
    )
    op.create_index(op.f('ix_appointment_reason_appointment_id'), 'appointment_reason', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_appointment_reason_reference_appointment_id'), table_name='appointment_reason_reference')
    op.drop_table('appointment_reason_reference')
    op.drop_index(op.f('ix_appointment_reason_code_appointment_id'), table_name='appointment_reason_code')
    op.drop_table('appointment_reason_code')
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
