"""healthcare_service_rework

Revision ID: cb20e4c5af59
Revises: ad5a4b97064d
Create Date: 2026-09-02 15:01:20.115355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb20e4c5af59'
down_revision: Union[str, None] = 'ad5a4b97064d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_type_system', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_type_version', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_type_code', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_type_display', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_type_text', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_system', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_value', sa.String(), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service', sa.Column('provided_by_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('healthcare_service', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('healthcare_service_pub_seq'::regclass)"))
    op.alter_column('healthcare_service', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthcare_service', 'provided_by_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthcare_service', 'comment',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'photo_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'availability_exceptions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_healthcare_service_provided_by_id'), table_name='healthcare_service')
    op.drop_index(op.f('ix_healthcare_service_user_id'), table_name='healthcare_service')
    op.drop_constraint(op.f('healthcare_service_provided_by_id_fkey'), 'healthcare_service', type_='foreignkey')
    op.drop_column('healthcare_service', 'user_id')
    op.add_column('healthcare_service_available_time', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_available_time', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_available_time', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_available_time', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_available_time', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_available_time', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_available_time', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthcare_service_available_time', 'available_start_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using='available_start_time::time')
    op.alter_column('healthcare_service_available_time', 'available_end_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using='available_end_time::time')
    op.add_column('healthcare_service_category', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_category', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_category', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_category', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_category', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_category', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_category', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_characteristic', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_characteristic', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_characteristic', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_characteristic', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_characteristic', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_characteristic', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_characteristic', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_characteristic', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_characteristic', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_communication', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_communication', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_communication', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_communication', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_communication', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_communication', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_communication', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_communication', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_communication', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_coverage_area', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_coverage_area', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_coverage_area', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_coverage_area', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_coverage_area', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Renamed PG enum type — alter_column can't cast to a not-yet-existent
    # type name, so rename the existing type in place instead (values unchanged).
    op.execute('ALTER TYPE hs_coverage_area_ref_type RENAME TO healthcare_service_coverage_area_reference_type')
    op.alter_column('healthcare_service_coverage_area', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_healthcare_service_coverage_area_reference_id'), table_name='healthcare_service_coverage_area')
    op.create_unique_constraint('uq_healthcare_service_coverage_area_reference', 'healthcare_service_coverage_area', ['healthcare_service_id', 'reference_type', 'reference_id'])
    op.drop_constraint(op.f('healthcare_service_coverage_area_reference_id_fkey'), 'healthcare_service_coverage_area', type_='foreignkey')
    op.add_column('healthcare_service_eligibility', sa.Column('code_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_eligibility', sa.Column('code_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_eligibility', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_eligibility', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_eligibility', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_eligibility', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_eligibility', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_eligibility', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_eligibility', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_endpoint', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_endpoint', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_endpoint', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_endpoint', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Renamed PG enum type — see the coverage_area rename above.
    op.execute('ALTER TYPE hs_endpoint_ref_type RENAME TO healthcare_service_endpoint_reference_type')
    op.alter_column('healthcare_service_endpoint', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_unique_constraint('uq_healthcare_service_endpoint_reference', 'healthcare_service_endpoint', ['healthcare_service_id', 'reference_type', 'reference_id'])
    op.add_column('healthcare_service_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_type', postgresql.ENUM('Organization', name='organization_reference_type', create_type=False), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_id', sa.BigInteger(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_identifier', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthcare_service_identifier', 'use',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False),
               existing_nullable=True,
               postgresql_using='use::text::identifier_use')
    op.create_unique_constraint('uq_healthcare_service_identifier_system_value', 'healthcare_service_identifier', ['system', 'value'])
    op.drop_column('healthcare_service_identifier', 'assigner')
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_type_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_type_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_type_code', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_type_display', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_type_text', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_system', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_value', sa.String(), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('reference_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_location', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_location', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_location', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_location', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_location', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Renamed PG enum type — see the coverage_area rename above.
    op.execute('ALTER TYPE hs_location_ref_type RENAME TO healthcare_service_location_reference_type')
    op.alter_column('healthcare_service_location', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_healthcare_service_location_reference_id'), table_name='healthcare_service_location')
    op.create_unique_constraint('uq_healthcare_service_location_reference', 'healthcare_service_location', ['healthcare_service_id', 'reference_type', 'reference_id'])
    op.drop_constraint(op.f('healthcare_service_location_reference_id_fkey'), 'healthcare_service_location', type_='foreignkey')
    op.add_column('healthcare_service_not_available', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_not_available', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_not_available', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_not_available', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_not_available', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_not_available', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_not_available', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_program', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_program', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_program', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_program', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_program', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_program', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_program', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_program', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_program', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_referral_method', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_referral_method', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_referral_method', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_referral_method', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_referral_method', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_referral_method', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_referral_method', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_referral_method', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_referral_method', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_service_provision_code', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_service_provision_code', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_service_provision_code', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_service_provision_code', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_service_provision_code', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_service_provision_code', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_service_provision_code', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_service_provision_code', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_service_provision_code', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_specialty', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_specialty', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_specialty', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_specialty', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_specialty', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_specialty', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_specialty', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_specialty', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_specialty', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_telecom', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_telecom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_telecom', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_telecom', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_telecom', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_telecom', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('healthcare_service_type', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('healthcare_service_type', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('healthcare_service_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('healthcare_service_type', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('healthcare_service_type', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('healthcare_service_type', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('healthcare_service_type', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('healthcare_service_type', 'healthcare_service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('healthcare_service_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_role_healthcare_service', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practitioner_role_healthcare_service', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('healthcare_service_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_type', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_type', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_type', 'updated_by')
    op.drop_column('healthcare_service_type', 'created_by')
    op.drop_column('healthcare_service_type', 'updated_at')
    op.drop_column('healthcare_service_type', 'created_at')
    op.drop_column('healthcare_service_type', 'coding_user_selected')
    op.drop_column('healthcare_service_type', 'coding_version')
    op.alter_column('healthcare_service_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_telecom', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_telecom', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_telecom', 'updated_by')
    op.drop_column('healthcare_service_telecom', 'created_by')
    op.drop_column('healthcare_service_telecom', 'updated_at')
    op.drop_column('healthcare_service_telecom', 'created_at')
    op.alter_column('healthcare_service_specialty', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_specialty', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_specialty', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_specialty', 'updated_by')
    op.drop_column('healthcare_service_specialty', 'created_by')
    op.drop_column('healthcare_service_specialty', 'updated_at')
    op.drop_column('healthcare_service_specialty', 'created_at')
    op.drop_column('healthcare_service_specialty', 'coding_user_selected')
    op.drop_column('healthcare_service_specialty', 'coding_version')
    op.alter_column('healthcare_service_service_provision_code', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_service_provision_code', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_service_provision_code', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_service_provision_code', 'updated_by')
    op.drop_column('healthcare_service_service_provision_code', 'created_by')
    op.drop_column('healthcare_service_service_provision_code', 'updated_at')
    op.drop_column('healthcare_service_service_provision_code', 'created_at')
    op.drop_column('healthcare_service_service_provision_code', 'coding_user_selected')
    op.drop_column('healthcare_service_service_provision_code', 'coding_version')
    op.alter_column('healthcare_service_referral_method', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_referral_method', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_referral_method', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_referral_method', 'updated_by')
    op.drop_column('healthcare_service_referral_method', 'created_by')
    op.drop_column('healthcare_service_referral_method', 'updated_at')
    op.drop_column('healthcare_service_referral_method', 'created_at')
    op.drop_column('healthcare_service_referral_method', 'coding_user_selected')
    op.drop_column('healthcare_service_referral_method', 'coding_version')
    op.alter_column('healthcare_service_program', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_program', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_program', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_program', 'updated_by')
    op.drop_column('healthcare_service_program', 'created_by')
    op.drop_column('healthcare_service_program', 'updated_at')
    op.drop_column('healthcare_service_program', 'created_at')
    op.drop_column('healthcare_service_program', 'coding_user_selected')
    op.drop_column('healthcare_service_program', 'coding_version')
    op.alter_column('healthcare_service_not_available', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_not_available', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_not_available', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_not_available', 'updated_by')
    op.drop_column('healthcare_service_not_available', 'created_by')
    op.drop_column('healthcare_service_not_available', 'updated_at')
    op.drop_column('healthcare_service_not_available', 'created_at')
    op.create_foreign_key(op.f('healthcare_service_location_reference_id_fkey'), 'healthcare_service_location', 'location', ['reference_id'], ['id'])
    op.drop_constraint('uq_healthcare_service_location_reference', 'healthcare_service_location', type_='unique')
    op.create_index(op.f('ix_healthcare_service_location_reference_id'), 'healthcare_service_location', ['reference_id'], unique=False)
    op.alter_column('healthcare_service_location', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.execute('ALTER TYPE healthcare_service_location_reference_type RENAME TO hs_location_ref_type')
    op.alter_column('healthcare_service_location', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_location', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_location', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_location', 'updated_by')
    op.drop_column('healthcare_service_location', 'created_by')
    op.drop_column('healthcare_service_location', 'updated_at')
    op.drop_column('healthcare_service_location', 'created_at')
    op.drop_column('healthcare_service_location', 'reference_identifier_period_end')
    op.drop_column('healthcare_service_location', 'reference_identifier_period_start')
    op.drop_column('healthcare_service_location', 'reference_identifier_value')
    op.drop_column('healthcare_service_location', 'reference_identifier_system')
    op.drop_column('healthcare_service_location', 'reference_identifier_type_user_selected')
    op.drop_column('healthcare_service_location', 'reference_identifier_type_text')
    op.drop_column('healthcare_service_location', 'reference_identifier_type_display')
    op.drop_column('healthcare_service_location', 'reference_identifier_type_code')
    op.drop_column('healthcare_service_location', 'reference_identifier_type_version')
    op.drop_column('healthcare_service_location', 'reference_identifier_type_system')
    op.drop_column('healthcare_service_location', 'reference_identifier_use')
    op.add_column('healthcare_service_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_healthcare_service_identifier_system_value', 'healthcare_service_identifier', type_='unique')
    op.alter_column('healthcare_service_identifier', 'use',
               existing_type=postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='use::text')
    op.alter_column('healthcare_service_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_identifier', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_identifier', 'updated_by')
    op.drop_column('healthcare_service_identifier', 'created_by')
    op.drop_column('healthcare_service_identifier', 'updated_at')
    op.drop_column('healthcare_service_identifier', 'created_at')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_period_end')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_period_start')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_value')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_system')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_type_text')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_type_display')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_type_code')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_type_version')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_type_system')
    op.drop_column('healthcare_service_identifier', 'assigner_identifier_use')
    op.drop_column('healthcare_service_identifier', 'assigner_display')
    op.drop_column('healthcare_service_identifier', 'assigner_id')
    op.drop_column('healthcare_service_identifier', 'assigner_type')
    op.drop_column('healthcare_service_identifier', 'type_user_selected')
    op.drop_column('healthcare_service_identifier', 'type_version')
    op.drop_constraint('uq_healthcare_service_endpoint_reference', 'healthcare_service_endpoint', type_='unique')
    op.alter_column('healthcare_service_endpoint', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.execute('ALTER TYPE healthcare_service_endpoint_reference_type RENAME TO hs_endpoint_ref_type')
    op.alter_column('healthcare_service_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_endpoint', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_endpoint', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_endpoint', 'updated_by')
    op.drop_column('healthcare_service_endpoint', 'created_by')
    op.drop_column('healthcare_service_endpoint', 'updated_at')
    op.drop_column('healthcare_service_endpoint', 'created_at')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_period_end')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_period_start')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_value')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_system')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_type_user_selected')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_type_text')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_type_display')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_type_code')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_type_version')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_type_system')
    op.drop_column('healthcare_service_endpoint', 'reference_identifier_use')
    op.alter_column('healthcare_service_eligibility', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_eligibility', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_eligibility', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_eligibility', 'updated_by')
    op.drop_column('healthcare_service_eligibility', 'created_by')
    op.drop_column('healthcare_service_eligibility', 'updated_at')
    op.drop_column('healthcare_service_eligibility', 'created_at')
    op.drop_column('healthcare_service_eligibility', 'code_user_selected')
    op.drop_column('healthcare_service_eligibility', 'code_version')
    op.create_foreign_key(op.f('healthcare_service_coverage_area_reference_id_fkey'), 'healthcare_service_coverage_area', 'location', ['reference_id'], ['id'])
    op.drop_constraint('uq_healthcare_service_coverage_area_reference', 'healthcare_service_coverage_area', type_='unique')
    op.create_index(op.f('ix_healthcare_service_coverage_area_reference_id'), 'healthcare_service_coverage_area', ['reference_id'], unique=False)
    op.alter_column('healthcare_service_coverage_area', 'reference_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.execute('ALTER TYPE healthcare_service_coverage_area_reference_type RENAME TO hs_coverage_area_ref_type')
    op.alter_column('healthcare_service_coverage_area', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_coverage_area', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_coverage_area', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_coverage_area', 'updated_by')
    op.drop_column('healthcare_service_coverage_area', 'created_by')
    op.drop_column('healthcare_service_coverage_area', 'updated_at')
    op.drop_column('healthcare_service_coverage_area', 'created_at')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_period_end')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_period_start')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_value')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_system')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_type_user_selected')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_type_text')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_type_display')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_type_code')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_type_version')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_type_system')
    op.drop_column('healthcare_service_coverage_area', 'reference_identifier_use')
    op.alter_column('healthcare_service_communication', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_communication', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_communication', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_communication', 'updated_by')
    op.drop_column('healthcare_service_communication', 'created_by')
    op.drop_column('healthcare_service_communication', 'updated_at')
    op.drop_column('healthcare_service_communication', 'created_at')
    op.drop_column('healthcare_service_communication', 'coding_user_selected')
    op.drop_column('healthcare_service_communication', 'coding_version')
    op.alter_column('healthcare_service_characteristic', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_characteristic', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_characteristic', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_characteristic', 'updated_by')
    op.drop_column('healthcare_service_characteristic', 'created_by')
    op.drop_column('healthcare_service_characteristic', 'updated_at')
    op.drop_column('healthcare_service_characteristic', 'created_at')
    op.drop_column('healthcare_service_characteristic', 'coding_user_selected')
    op.drop_column('healthcare_service_characteristic', 'coding_version')
    op.alter_column('healthcare_service_category', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_category', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_category', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_category', 'updated_by')
    op.drop_column('healthcare_service_category', 'created_by')
    op.drop_column('healthcare_service_category', 'updated_at')
    op.drop_column('healthcare_service_category', 'created_at')
    op.drop_column('healthcare_service_category', 'coding_user_selected')
    op.drop_column('healthcare_service_category', 'coding_version')
    op.alter_column('healthcare_service_available_time', 'available_end_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='available_end_time::varchar')
    op.alter_column('healthcare_service_available_time', 'available_start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='available_start_time::varchar')
    op.alter_column('healthcare_service_available_time', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service_available_time', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('healthcare_service_available_time', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service_available_time', 'updated_by')
    op.drop_column('healthcare_service_available_time', 'created_by')
    op.drop_column('healthcare_service_available_time', 'updated_at')
    op.drop_column('healthcare_service_available_time', 'created_at')
    op.add_column('healthcare_service', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('healthcare_service_provided_by_id_fkey'), 'healthcare_service', 'organization', ['provided_by_id'], ['id'])
    op.create_index(op.f('ix_healthcare_service_user_id'), 'healthcare_service', ['user_id'], unique=False)
    op.create_index(op.f('ix_healthcare_service_provided_by_id'), 'healthcare_service', ['provided_by_id'], unique=False)
    op.alter_column('healthcare_service', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service', 'availability_exceptions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'photo_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service', 'provided_by_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('healthcare_service', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthcare_service', 'healthcare_service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('healthcare_service_pub_seq'::regclass)"))
    op.alter_column('healthcare_service', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('healthcare_service', 'provided_by_identifier_period_end')
    op.drop_column('healthcare_service', 'provided_by_identifier_period_start')
    op.drop_column('healthcare_service', 'provided_by_identifier_value')
    op.drop_column('healthcare_service', 'provided_by_identifier_system')
    op.drop_column('healthcare_service', 'provided_by_identifier_type_user_selected')
    op.drop_column('healthcare_service', 'provided_by_identifier_type_text')
    op.drop_column('healthcare_service', 'provided_by_identifier_type_display')
    op.drop_column('healthcare_service', 'provided_by_identifier_type_code')
    op.drop_column('healthcare_service', 'provided_by_identifier_type_version')
    op.drop_column('healthcare_service', 'provided_by_identifier_type_system')
    op.drop_column('healthcare_service', 'provided_by_identifier_use')
    # ### end Alembic commands ###
