"""encounter_r4_rewrite

Revision ID: d6c9ce92f33f
Revises: 2048fe9a4c8d
Create Date: 2026-07-26 15:08:53.042809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c9ce92f33f'
down_revision: Union[str, None] = '2048fe9a4c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')

    # Encounter is being rewritten wholesale from FHIR R5 shape to R4 shape.
    # The 3 existing dev rows are R5-shaped (status='completed', not a valid
    # R4 code) and can't be carried forward — clear them and all sub-resource
    # children before changing enum value sets, so no USING-cast data loss
    # decisions are needed on the swaps below.
    op.execute('TRUNCATE TABLE encounter CASCADE')

    # ── Narrow/replace enum value sets (R5 -> R4) via rename-swap, since
    # Postgres can't remove values from an existing enum type in place ──
    op.execute('ALTER TYPE encounter_status RENAME TO encounter_status_old')
    op.execute(
        "CREATE TYPE encounter_status AS ENUM "
        "('planned', 'arrived', 'triaged', 'in-progress', 'onleave', 'finished', 'cancelled', 'entered-in-error', 'unknown')"
    )
    op.execute('ALTER TABLE encounter ALTER COLUMN status TYPE encounter_status USING status::text::encounter_status')
    op.execute('DROP TYPE encounter_status_old')

    op.execute('ALTER TYPE encounter_participant_reference_type RENAME TO encounter_participant_reference_type_old')
    op.execute("CREATE TYPE encounter_participant_reference_type AS ENUM ('Practitioner', 'PractitionerRole', 'RelatedPerson')")
    op.execute('ALTER TABLE encounter_participant ALTER COLUMN reference_type TYPE encounter_participant_reference_type USING reference_type::text::encounter_participant_reference_type')
    op.execute('DROP TYPE encounter_participant_reference_type_old')

    op.execute('ALTER TYPE encounter_based_on_reference_type RENAME TO encounter_based_on_reference_type_old')
    op.execute("CREATE TYPE encounter_based_on_reference_type AS ENUM ('ServiceRequest')")
    op.execute('ALTER TABLE encounter_based_on ALTER COLUMN reference_type TYPE encounter_based_on_reference_type USING reference_type::text::encounter_based_on_reference_type')
    op.execute('DROP TYPE encounter_based_on_reference_type_old')

    op.create_table('encounter_reason_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('coding_system', sa.String(), nullable=True),
    sa.Column('coding_code', sa.String(), nullable=True),
    sa.Column('coding_display', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_reason_code_encounter_id'), 'encounter_reason_code', ['encounter_id'], unique=False)
    op.create_table('encounter_reason_reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.Enum('Condition', 'Procedure', 'Observation', 'ImmunizationRecommendation', name='encounter_reason_reference_type'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_reason_reference_encounter_id'), 'encounter_reason_reference', ['encounter_id'], unique=False)
    op.drop_index(op.f('ix_encounter_reason_use_reason_id'), table_name='encounter_reason_use')
    op.drop_table('encounter_reason_use')
    op.drop_index(op.f('ix_encounter_virtual_service_encounter_id'), table_name='encounter_virtual_service')
    op.drop_table('encounter_virtual_service')
    op.drop_index(op.f('ix_encounter_care_team_encounter_id'), table_name='encounter_care_team')
    op.drop_table('encounter_care_team')
    op.execute('DROP TYPE encounter_care_team_reference_type')
    op.drop_index(op.f('ix_encounter_diagnosis_condition_diagnosis_id'), table_name='encounter_diagnosis_condition')
    op.drop_table('encounter_diagnosis_condition')
    op.execute('DROP TYPE encounter_diagnosis_condition_type')
    op.drop_index(op.f('ix_encounter_reason_value_reason_id'), table_name='encounter_reason_value')
    op.drop_table('encounter_reason_value')
    op.execute('DROP TYPE encounter_reason_value_reference_type')
    op.drop_index(op.f('ix_encounter_service_type_encounter_id'), table_name='encounter_service_type')
    op.drop_table('encounter_service_type')
    op.execute('DROP TYPE encounter_service_type_reference_type')
    op.drop_index(op.f('ix_encounter_reason_encounter_id'), table_name='encounter_reason')
    op.drop_table('encounter_reason')
    op.drop_index(op.f('ix_encounter_business_status_encounter_id'), table_name='encounter_business_status')
    op.drop_table('encounter_business_status')
    op.drop_index(op.f('ix_encounter_class_encounter_id'), table_name='encounter_class')
    op.drop_table('encounter_class')
    op.drop_index(op.f('ix_encounter_diagnosis_use_diagnosis_id'), table_name='encounter_diagnosis_use')
    op.drop_table('encounter_diagnosis_use')
    op.add_column('encounter', sa.Column('class_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('class_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('class_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('service_type_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounter', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_pre_admission_identifier_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_pre_admission_identifier_value', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_origin_type', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_origin_id', sa.Integer(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_origin_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_admit_source_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_admit_source_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_admit_source_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_admit_source_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_re_admission_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_re_admission_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_re_admission_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_re_admission_text', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_destination_type', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_destination_id', sa.Integer(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_destination_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_discharge_disposition_system', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_discharge_disposition_code', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_discharge_disposition_display', sa.String(), nullable=True))
    op.add_column('encounter', sa.Column('hospitalization_discharge_disposition_text', sa.String(), nullable=True))
    op.create_index(op.f('ix_encounter_part_of_id'), 'encounter', ['part_of_id'], unique=False)
    op.create_index(op.f('ix_encounter_service_provider_id'), 'encounter', ['service_provider_id'], unique=False)
    op.create_foreign_key(None, 'encounter', 'encounter', ['part_of_id'], ['id'])
    op.create_foreign_key(None, 'encounter', 'organization', ['service_provider_id'], ['id'])
    op.drop_column('encounter', 'planned_start_date')
    op.drop_column('encounter', 'subject_status_display')
    op.drop_column('encounter', 'admission_pre_admission_identifier_value')
    op.drop_column('encounter', 'actual_period_start')
    op.drop_column('encounter', 'admission_admit_source_text')
    op.drop_column('encounter', 'admission_discharge_disposition_code')
    op.drop_column('encounter', 'subject_status_text')
    op.drop_column('encounter', 'admission_admit_source_code')
    op.drop_column('encounter', 'admission_origin_id')
    op.drop_column('encounter', 'admission_origin_type')
    op.drop_column('encounter', 'admission_origin_display')
    op.drop_column('encounter', 'admission_admit_source_display')
    op.drop_column('encounter', 'admission_re_admission_system')
    op.drop_column('encounter', 'admission_pre_admission_identifier_system')
    op.drop_column('encounter', 'admission_admit_source_system')
    op.drop_column('encounter', 'admission_re_admission_display')
    op.drop_column('encounter', 'subject_status_system')
    op.drop_column('encounter', 'admission_destination_display')
    op.drop_column('encounter', 'admission_discharge_disposition_text')
    op.drop_column('encounter', 'admission_destination_type')
    op.drop_column('encounter', 'subject_status_code')
    op.drop_column('encounter', 'admission_discharge_disposition_display')
    op.drop_column('encounter', 'admission_destination_id')
    op.drop_column('encounter', 'admission_discharge_disposition_system')
    op.drop_column('encounter', 'actual_period_end')
    op.drop_column('encounter', 'admission_re_admission_text')
    op.drop_column('encounter', 'planned_end_date')
    op.drop_column('encounter', 'admission_re_admission_code')
    op.execute("CREATE TYPE encounter_diagnosis_condition_type AS ENUM ('Condition', 'Procedure')")
    op.add_column('encounter_diagnosis', sa.Column('condition_type', postgresql.ENUM('Condition', 'Procedure', name='encounter_diagnosis_condition_type', create_type=False), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('condition_id', sa.Integer(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('condition_display', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_system', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_code', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_display', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('use_text', sa.String(), nullable=True))
    op.add_column('encounter_diagnosis', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_system', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_code', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_display', sa.String(), nullable=True))
    op.add_column('encounter_location', sa.Column('physical_type_text', sa.String(), nullable=True))
    op.drop_column('encounter_location', 'form_text')
    op.drop_column('encounter_location', 'form_display')
    op.drop_column('encounter_location', 'form_code')
    op.drop_column('encounter_location', 'form_system')
    op.alter_column('encounter_status_history', 'status',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('planned', 'arrived', 'triaged', 'in_progress', 'onleave', 'finished', 'cancelled', 'entered_in_error', 'unknown', name='encounter_status', create_type=False),
               existing_nullable=False,
               postgresql_using='status::text::encounter_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE encounter CASCADE')

    op.alter_column('encounter_status_history', 'status',
               existing_type=postgresql.ENUM('planned', 'arrived', 'triaged', 'in_progress', 'onleave', 'finished', 'cancelled', 'entered_in_error', 'unknown', name='encounter_status', create_type=False),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='status::text')
    op.add_column('encounter_location', sa.Column('form_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter_location', sa.Column('form_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter_location', sa.Column('form_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter_location', sa.Column('form_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('encounter_location', 'physical_type_text')
    op.drop_column('encounter_location', 'physical_type_display')
    op.drop_column('encounter_location', 'physical_type_code')
    op.drop_column('encounter_location', 'physical_type_system')
    op.drop_column('encounter_diagnosis', 'rank')
    op.drop_column('encounter_diagnosis', 'use_text')
    op.drop_column('encounter_diagnosis', 'use_display')
    op.drop_column('encounter_diagnosis', 'use_code')
    op.drop_column('encounter_diagnosis', 'use_system')
    op.drop_column('encounter_diagnosis', 'condition_display')
    op.drop_column('encounter_diagnosis', 'condition_id')
    op.drop_column('encounter_diagnosis', 'condition_type')
    op.execute('DROP TYPE encounter_diagnosis_condition_type')
    op.add_column('encounter', sa.Column('admission_re_admission_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('planned_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_re_admission_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('actual_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_discharge_disposition_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_destination_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_discharge_disposition_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('subject_status_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_destination_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_discharge_disposition_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_destination_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('subject_status_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_re_admission_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_admit_source_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_pre_admission_identifier_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_re_admission_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_admit_source_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_origin_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_origin_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_origin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_admit_source_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('subject_status_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_discharge_disposition_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_admit_source_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('actual_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('admission_pre_admission_identifier_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('subject_status_display', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('planned_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'encounter', type_='foreignkey')
    op.drop_constraint(None, 'encounter', type_='foreignkey')
    op.drop_index(op.f('ix_encounter_service_provider_id'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_part_of_id'), table_name='encounter')
    op.drop_column('encounter', 'hospitalization_discharge_disposition_text')
    op.drop_column('encounter', 'hospitalization_discharge_disposition_display')
    op.drop_column('encounter', 'hospitalization_discharge_disposition_code')
    op.drop_column('encounter', 'hospitalization_discharge_disposition_system')
    op.drop_column('encounter', 'hospitalization_destination_display')
    op.drop_column('encounter', 'hospitalization_destination_id')
    op.drop_column('encounter', 'hospitalization_destination_type')
    op.drop_column('encounter', 'hospitalization_re_admission_text')
    op.drop_column('encounter', 'hospitalization_re_admission_display')
    op.drop_column('encounter', 'hospitalization_re_admission_code')
    op.drop_column('encounter', 'hospitalization_re_admission_system')
    op.drop_column('encounter', 'hospitalization_admit_source_text')
    op.drop_column('encounter', 'hospitalization_admit_source_display')
    op.drop_column('encounter', 'hospitalization_admit_source_code')
    op.drop_column('encounter', 'hospitalization_admit_source_system')
    op.drop_column('encounter', 'hospitalization_origin_display')
    op.drop_column('encounter', 'hospitalization_origin_id')
    op.drop_column('encounter', 'hospitalization_origin_type')
    op.drop_column('encounter', 'hospitalization_pre_admission_identifier_value')
    op.drop_column('encounter', 'hospitalization_pre_admission_identifier_system')
    op.drop_column('encounter', 'period_end')
    op.drop_column('encounter', 'period_start')
    op.drop_column('encounter', 'service_type_text')
    op.drop_column('encounter', 'service_type_display')
    op.drop_column('encounter', 'service_type_code')
    op.drop_column('encounter', 'service_type_system')
    op.drop_column('encounter', 'class_display')
    op.drop_column('encounter', 'class_code')
    op.drop_column('encounter', 'class_system')
    op.create_table('encounter_diagnosis_use',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('diagnosis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['encounter_diagnosis.id'], name=op.f('encounter_diagnosis_use_diagnosis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_diagnosis_use_pkey'))
    )
    op.create_index(op.f('ix_encounter_diagnosis_use_diagnosis_id'), 'encounter_diagnosis_use', ['diagnosis_id'], unique=False)
    op.create_table('encounter_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('encounter_class_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_class_pkey'))
    )
    op.create_index(op.f('ix_encounter_class_encounter_id'), 'encounter_class', ['encounter_id'], unique=False)
    op.create_table('encounter_business_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('encounter_business_status_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_business_status_pkey'))
    )
    op.create_index(op.f('ix_encounter_business_status_encounter_id'), 'encounter_business_status', ['encounter_id'], unique=False)
    op.create_table('encounter_reason',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('encounter_reason_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_reason_pkey'))
    )
    op.create_index(op.f('ix_encounter_reason_encounter_id'), 'encounter_reason', ['encounter_id'], unique=False)
    op.execute("CREATE TYPE encounter_service_type_reference_type AS ENUM ('HealthcareService')")
    op.create_table('encounter_service_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('HealthcareService', name='encounter_service_type_reference_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('encounter_service_type_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_service_type_pkey'))
    )
    op.create_index(op.f('ix_encounter_service_type_encounter_id'), 'encounter_service_type', ['encounter_id'], unique=False)
    op.execute("CREATE TYPE encounter_reason_value_reference_type AS ENUM ('Condition', 'DiagnosticReport', 'Observation', 'Procedure')")
    op.create_table('encounter_reason_value',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reason_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('Condition', 'DiagnosticReport', 'Observation', 'Procedure', name='encounter_reason_value_reference_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reason_id'], ['encounter_reason.id'], name=op.f('encounter_reason_value_reason_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_reason_value_pkey'))
    )
    op.create_index(op.f('ix_encounter_reason_value_reason_id'), 'encounter_reason_value', ['reason_id'], unique=False)
    op.execute("CREATE TYPE encounter_diagnosis_condition_type AS ENUM ('Condition')")
    op.create_table('encounter_diagnosis_condition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('diagnosis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('Condition', name='encounter_diagnosis_condition_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['encounter_diagnosis.id'], name=op.f('encounter_diagnosis_condition_diagnosis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_diagnosis_condition_pkey'))
    )
    op.create_index(op.f('ix_encounter_diagnosis_condition_diagnosis_id'), 'encounter_diagnosis_condition', ['diagnosis_id'], unique=False)
    op.execute("CREATE TYPE encounter_care_team_reference_type AS ENUM ('CareTeam')")
    op.create_table('encounter_care_team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_type', postgresql.ENUM('CareTeam', name='encounter_care_team_reference_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('encounter_care_team_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_care_team_pkey'))
    )
    op.create_index(op.f('ix_encounter_care_team_encounter_id'), 'encounter_care_team', ['encounter_id'], unique=False)
    op.create_table('encounter_virtual_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.id'], name=op.f('encounter_virtual_service_encounter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_virtual_service_pkey'))
    )
    op.create_index(op.f('ix_encounter_virtual_service_encounter_id'), 'encounter_virtual_service', ['encounter_id'], unique=False)
    op.create_table('encounter_reason_use',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reason_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_system', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coding_display', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reason_id'], ['encounter_reason.id'], name=op.f('encounter_reason_use_reason_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encounter_reason_use_pkey'))
    )
    op.create_index(op.f('ix_encounter_reason_use_reason_id'), 'encounter_reason_use', ['reason_id'], unique=False)
    op.drop_index(op.f('ix_encounter_reason_reference_encounter_id'), table_name='encounter_reason_reference')
    op.drop_table('encounter_reason_reference')
    op.drop_index(op.f('ix_encounter_reason_code_encounter_id'), table_name='encounter_reason_code')
    op.drop_table('encounter_reason_code')

    op.execute('ALTER TYPE encounter_based_on_reference_type RENAME TO encounter_based_on_reference_type_new')
    op.execute(
        "CREATE TYPE encounter_based_on_reference_type AS ENUM "
        "('CarePlan', 'DeviceRequest', 'MedicationRequest', 'ServiceRequest', 'RequestOrchestration', 'NutritionOrder', 'VisionPrescription')"
    )
    op.execute('ALTER TABLE encounter_based_on ALTER COLUMN reference_type TYPE encounter_based_on_reference_type USING reference_type::text::encounter_based_on_reference_type')
    op.execute('DROP TYPE encounter_based_on_reference_type_new')

    op.execute('ALTER TYPE encounter_participant_reference_type RENAME TO encounter_participant_reference_type_new')
    op.execute(
        "CREATE TYPE encounter_participant_reference_type AS ENUM "
        "('Patient', 'Group', 'RelatedPerson', 'Practitioner', 'PractitionerRole', 'Device', 'HealthcareService')"
    )
    op.execute('ALTER TABLE encounter_participant ALTER COLUMN reference_type TYPE encounter_participant_reference_type USING reference_type::text::encounter_participant_reference_type')
    op.execute('DROP TYPE encounter_participant_reference_type_new')

    op.execute('ALTER TYPE encounter_status RENAME TO encounter_status_new')
    op.execute(
        "CREATE TYPE encounter_status AS ENUM "
        "('planned', 'in-progress', 'on-hold', 'discharged', 'completed', 'cancelled', 'discontinued', 'entered-in-error', 'unknown')"
    )
    op.execute('ALTER TABLE encounter ALTER COLUMN status TYPE encounter_status USING status::text::encounter_status')
    op.execute('ALTER TABLE encounter_status_history ALTER COLUMN status TYPE encounter_status USING status::text::encounter_status')
    op.execute('DROP TYPE encounter_status_new')
    # ### end Alembic commands ###
