"""healthcare_service provided_by/location/coverage_area fk resolver

Revision ID: dace158bf419
Revises: 324aeb37f590
Create Date: 2026-07-26 17:08:52.815257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dace158bf419'
down_revision: Union[str, None] = '324aeb37f590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    # Backfill: reference_id/provided_by_id currently store the raw public sequence
    # id the client sent (e.g. Organization/190001 -> 190001), not the target row's
    # internal PK. Translate forward before adding the FK, or the FK add will fail
    # (and any existing rows would silently mismatch on join).
    op.execute("""
        UPDATE healthcare_service AS hs
        SET provided_by_id = org.id
        FROM organization AS org
        WHERE hs.provided_by_id IS NOT NULL
          AND org.organization_id = hs.provided_by_id
    """)
    op.execute("""
        UPDATE healthcare_service_location AS hsl
        SET reference_id = loc.id
        FROM location AS loc
        WHERE hsl.reference_id IS NOT NULL
          AND loc.location_id = hsl.reference_id
    """)
    op.execute("""
        UPDATE healthcare_service_coverage_area AS hca
        SET reference_id = loc.id
        FROM location AS loc
        WHERE hca.reference_id IS NOT NULL
          AND loc.location_id = hca.reference_id
    """)

    op.create_index(op.f('ix_healthcare_service_provided_by_id'), 'healthcare_service', ['provided_by_id'], unique=False)
    op.create_foreign_key(None, 'healthcare_service', 'organization', ['provided_by_id'], ['id'])
    op.create_index(op.f('ix_healthcare_service_coverage_area_reference_id'), 'healthcare_service_coverage_area', ['reference_id'], unique=False)
    op.create_foreign_key(None, 'healthcare_service_coverage_area', 'location', ['reference_id'], ['id'])
    op.create_index(op.f('ix_healthcare_service_location_reference_id'), 'healthcare_service_location', ['reference_id'], unique=False)
    op.create_foreign_key(None, 'healthcare_service_location', 'location', ['reference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'healthcare_service_location', type_='foreignkey')
    op.drop_index(op.f('ix_healthcare_service_location_reference_id'), table_name='healthcare_service_location')
    op.drop_constraint(None, 'healthcare_service_coverage_area', type_='foreignkey')
    op.drop_index(op.f('ix_healthcare_service_coverage_area_reference_id'), table_name='healthcare_service_coverage_area')
    op.drop_constraint(None, 'healthcare_service', type_='foreignkey')
    op.drop_index(op.f('ix_healthcare_service_provided_by_id'), table_name='healthcare_service')

    # Translate back: internal PK -> raw public sequence id (reverse of upgrade's backfill)
    op.execute("""
        UPDATE healthcare_service AS hs
        SET provided_by_id = org.organization_id
        FROM organization AS org
        WHERE hs.provided_by_id IS NOT NULL
          AND org.id = hs.provided_by_id
    """)
    op.execute("""
        UPDATE healthcare_service_location AS hsl
        SET reference_id = loc.location_id
        FROM location AS loc
        WHERE hsl.reference_id IS NOT NULL
          AND loc.id = hsl.reference_id
    """)
    op.execute("""
        UPDATE healthcare_service_coverage_area AS hca
        SET reference_id = loc.location_id
        FROM location AS loc
        WHERE hca.reference_id IS NOT NULL
          AND loc.id = hca.reference_id
    """)
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
