"""slot_rework

Revision ID: dd86c3fb5aa3
Revises: a4f2c9d7e5b1
Create Date: 2026-09-03 11:49:54.952404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd86c3fb5aa3'
down_revision: Union[str, None] = 'a4f2c9d7e5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate's CREATE SEQUENCE IF NOT EXISTS noise for every other
    # resource's pub_seq (comparing full model metadata against the DB) has
    # been stripped — slot_pub_seq already exists in the live DB from the
    # pre-rework Slot model, and every other resource's sequence is
    # unrelated to this migration. See CLAUDE.md's migration gotchas.
    op.add_column('slot', sa.Column('schedule_id', sa.BigInteger(), nullable=False))
    op.add_column('slot', sa.Column('schedule_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_type_system', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_type_version', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_type_code', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_type_display', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_type_text', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_system', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_value', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot', sa.Column('schedule_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot', sa.Column('appointment_type_version', sa.String(), nullable=True))
    op.add_column('slot', sa.Column('appointment_type_user_selected', sa.Boolean(), nullable=True))
    op.alter_column('slot', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slot', 'slot_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('slot_pub_seq'::regclass)"))
    op.alter_column('slot', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('slot', 'schedule_type',
               existing_type=postgresql.ENUM('Schedule', name='slot_schedule_reference_type', create_type=False),
               nullable=False)
    op.alter_column('slot', 'start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('slot', 'end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('slot', 'comment',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('slot', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_slot_schedule_fk_id'), table_name='slot')
    op.drop_index(op.f('ix_slot_user_id'), table_name='slot')
    op.create_index(op.f('ix_slot_schedule_id'), 'slot', ['schedule_id'], unique=False)
    op.drop_constraint(op.f('slot_schedule_fk_id_fkey'), 'slot', type_='foreignkey')
    op.drop_column('slot', 'schedule_fk_id')
    op.drop_column('slot', 'user_id')
    op.add_column('slot_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_type', postgresql.ENUM('Organization', name='organization_reference_type', create_type=False), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_id', sa.BigInteger(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_use', postgresql.ENUM('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use', create_type=False), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('slot_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('slot_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('slot_identifier', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slot_identifier', 'slot_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('slot_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('slot_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_slot_identifier_assigner_id'), 'slot_identifier', ['assigner_id'], unique=False)
    op.create_unique_constraint('uq_slot_identifier_system_value', 'slot_identifier', ['system', 'value'])
    op.drop_column('slot_identifier', 'assigner')
    op.add_column('slot_service_category', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('slot_service_category', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('slot_service_category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('slot_service_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot_service_category', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('slot_service_category', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('slot_service_category', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slot_service_category', 'slot_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('slot_service_category', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('slot_service_type', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('slot_service_type', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('slot_service_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('slot_service_type', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot_service_type', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('slot_service_type', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('slot_service_type', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slot_service_type', 'slot_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('slot_service_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('slot_specialty', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('slot_specialty', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('slot_specialty', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('slot_specialty', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slot_specialty', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('slot_specialty', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('slot_specialty', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('slot_specialty', 'slot_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('slot_specialty', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slot_specialty', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot_specialty', 'slot_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('slot_specialty', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('slot_specialty', 'updated_by')
    op.drop_column('slot_specialty', 'created_by')
    op.drop_column('slot_specialty', 'updated_at')
    op.drop_column('slot_specialty', 'created_at')
    op.drop_column('slot_specialty', 'coding_user_selected')
    op.drop_column('slot_specialty', 'coding_version')
    op.alter_column('slot_service_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot_service_type', 'slot_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('slot_service_type', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('slot_service_type', 'updated_by')
    op.drop_column('slot_service_type', 'created_by')
    op.drop_column('slot_service_type', 'updated_at')
    op.drop_column('slot_service_type', 'created_at')
    op.drop_column('slot_service_type', 'coding_user_selected')
    op.drop_column('slot_service_type', 'coding_version')
    op.alter_column('slot_service_category', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot_service_category', 'slot_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('slot_service_category', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('slot_service_category', 'updated_by')
    op.drop_column('slot_service_category', 'created_by')
    op.drop_column('slot_service_category', 'updated_at')
    op.drop_column('slot_service_category', 'created_at')
    op.drop_column('slot_service_category', 'coding_user_selected')
    op.drop_column('slot_service_category', 'coding_version')
    op.add_column('slot_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_slot_identifier_system_value', 'slot_identifier', type_='unique')
    op.drop_index(op.f('ix_slot_identifier_assigner_id'), table_name='slot_identifier')
    op.alter_column('slot_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot_identifier', 'slot_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('slot_identifier', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('slot_identifier', 'updated_by')
    op.drop_column('slot_identifier', 'created_by')
    op.drop_column('slot_identifier', 'updated_at')
    op.drop_column('slot_identifier', 'created_at')
    op.drop_column('slot_identifier', 'assigner_identifier_period_end')
    op.drop_column('slot_identifier', 'assigner_identifier_period_start')
    op.drop_column('slot_identifier', 'assigner_identifier_value')
    op.drop_column('slot_identifier', 'assigner_identifier_system')
    op.drop_column('slot_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('slot_identifier', 'assigner_identifier_type_text')
    op.drop_column('slot_identifier', 'assigner_identifier_type_display')
    op.drop_column('slot_identifier', 'assigner_identifier_type_code')
    op.drop_column('slot_identifier', 'assigner_identifier_type_version')
    op.drop_column('slot_identifier', 'assigner_identifier_type_system')
    op.drop_column('slot_identifier', 'assigner_identifier_use')
    op.drop_column('slot_identifier', 'assigner_display')
    op.drop_column('slot_identifier', 'assigner_id')
    op.drop_column('slot_identifier', 'assigner_type')
    op.drop_column('slot_identifier', 'type_user_selected')
    op.drop_column('slot_identifier', 'type_version')
    op.add_column('slot', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('slot', sa.Column('schedule_fk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('slot_schedule_fk_id_fkey'), 'slot', 'schedule', ['schedule_fk_id'], ['id'])
    op.drop_index(op.f('ix_slot_schedule_id'), table_name='slot')
    op.create_index(op.f('ix_slot_user_id'), 'slot', ['user_id'], unique=False)
    op.create_index(op.f('ix_slot_schedule_fk_id'), 'slot', ['schedule_fk_id'], unique=False)
    op.alter_column('slot', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('slot', 'end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('slot', 'start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('slot', 'schedule_type',
               existing_type=postgresql.ENUM('Schedule', name='slot_schedule_reference_type', create_type=False),
               nullable=True)
    op.alter_column('slot', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slot', 'slot_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('slot_pub_seq'::regclass)"))
    op.alter_column('slot', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('slot', 'appointment_type_user_selected')
    op.drop_column('slot', 'appointment_type_version')
    op.drop_column('slot', 'schedule_identifier_period_end')
    op.drop_column('slot', 'schedule_identifier_period_start')
    op.drop_column('slot', 'schedule_identifier_value')
    op.drop_column('slot', 'schedule_identifier_system')
    op.drop_column('slot', 'schedule_identifier_type_user_selected')
    op.drop_column('slot', 'schedule_identifier_type_text')
    op.drop_column('slot', 'schedule_identifier_type_display')
    op.drop_column('slot', 'schedule_identifier_type_code')
    op.drop_column('slot', 'schedule_identifier_type_version')
    op.drop_column('slot', 'schedule_identifier_type_system')
    op.drop_column('slot', 'schedule_identifier_use')
    op.drop_column('slot', 'schedule_id')
    # NOTE: autogenerate's matching DROP SEQUENCE IF EXISTS noise for every
    # other resource's pub_seq has been stripped — see the note at the top
    # of upgrade().
    # ### end Alembic commands ###
