"""practitioner and organization identifier reference consistency

Revision ID: f65cde43f38e
Revises: 2dcc04f65495
Create Date: 2026-08-01 13:24:51.646193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f65cde43f38e'
down_revision: Union[str, None] = '2dcc04f65495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS allergy_intolerance_pub_seq START 260000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS appointment_pub_seq START 40000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS audit_event_pub_seq START 340000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS care_plan_pub_seq START 290000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_pub_seq START 170000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS claim_response_pub_seq START 180000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS condition_pub_seq START 120000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS coverage_pub_seq START 240000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS device_request_pub_seq START 130000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS diagnostic_report_pub_seq START 110000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS document_reference_pub_seq START 320000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS encounter_pub_seq START 20000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS episode_of_care_pub_seq START 350000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS healthcare_service_pub_seq START 150000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS immunization_pub_seq START 330000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS insurance_plan_pub_seq START 360000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS invoice_pub_seq START 210000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS location_pub_seq START 230000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_pub_seq START 250000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS medication_request_pub_seq START 90000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS observation_pub_seq START 160000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS organization_pub_seq START 190000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS patient_pub_seq START 10000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_pub_seq START 30000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS practitioner_role_pub_seq START 140000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS procedure_pub_seq START 100000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS provenance_pub_seq START 270000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS questionnaire_response_pub_seq START 60000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS related_person_pub_seq START 300000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS schedule_pub_seq START 200000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS service_request_pub_seq START 80000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS slot_pub_seq START 220000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS specimen_pub_seq START 310000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS task_pub_seq START 280000 INCREMENT 1')
    op.execute('CREATE SEQUENCE IF NOT EXISTS vitals_pub_seq START 70000 INCREMENT 1')
    op.add_column('organization', sa.Column('partof_identifier_use', sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_type_system', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_type_version', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_type_code', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_type_display', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_type_text', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_system', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_value', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization', sa.Column('partof_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('organization', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('organization_address', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_address', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_address', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_address', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_address', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'use',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('home', 'work', 'temp', 'old', 'billing', name='address_use'),
               existing_nullable=True,
               postgresql_using='use::address_use')
    op.alter_column('organization_address', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('postal', 'physical', 'both', name='address_type'),
               nullable=False,
               postgresql_using='type::address_type')
    op.alter_column('organization_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('organization_alias', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_alias', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_alias', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_alias', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_alias', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('organization_contact', sa.Column('purpose_version', sa.String(), nullable=True))
    op.add_column('organization_contact', sa.Column('purpose_user_selected', sa.Boolean(), nullable=True))
    op.add_column('organization_contact', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_contact', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_contact', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_contact', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_contact', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'name_use',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden', name='human_name_use'),
               existing_nullable=True,
               postgresql_using='name_use::human_name_use')
    op.alter_column('organization_contact', 'address_use',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('home', 'work', 'temp', 'old', 'billing', name='address_use'),
               existing_nullable=True,
               postgresql_using='address_use::address_use')
    op.alter_column('organization_contact', 'address_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('postal', 'physical', 'both', name='address_type'),
               nullable=False,
               postgresql_using='address_type::address_type')
    op.alter_column('organization_contact', 'address_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact', 'address_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('organization_contact_telecom', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_contact_telecom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_contact_telecom', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_contact_telecom', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_contact_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact_telecom', 'system',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False,
               postgresql_using='system::contact_point_system')
    op.alter_column('organization_contact_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_contact_telecom', 'use',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use'),
               existing_nullable=True,
               postgresql_using='use::contact_point_use')
    op.add_column('organization_endpoint', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_endpoint', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_endpoint', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_endpoint', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('organization_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_type', sa.Enum('Organization', name='organization_reference_type'), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_id', sa.Integer(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_use', sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_identifier', 'use',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'),
               existing_nullable=True,
               postgresql_using='use::identifier_use')
    op.alter_column('organization_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_organization_identifier_system_value', 'organization_identifier', ['system', 'value'])
    op.drop_column('organization_identifier', 'assigner')
    op.add_column('organization_telecom', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_telecom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_telecom', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_telecom', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_telecom', 'system',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False,
               postgresql_using='system::contact_point_system')
    op.alter_column('organization_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organization_telecom', 'use',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use'),
               existing_nullable=True,
               postgresql_using='use::contact_point_use')
    op.add_column('organization_type', sa.Column('coding_version', sa.String(), nullable=True))
    op.add_column('organization_type', sa.Column('coding_user_selected', sa.Boolean(), nullable=True))
    op.add_column('organization_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('organization_type', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_type', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('organization_type', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('organization_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('practitioner', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'unknown', name='administrative_gender'),
               nullable=False)
    op.alter_column('practitioner', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('practitioner', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_practitioner_org_id'), 'practitioner', ['org_id'], unique=False)
    op.create_unique_constraint('uq_practitioner_user_id_org_id', 'practitioner', ['user_id', 'org_id'])
    op.add_column('practitioner_address', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_address', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_address', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_address', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_address', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_address', 'type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type'),
               nullable=False)
    op.alter_column('practitioner_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_communication', sa.Column('language_version', sa.String(), nullable=True))
    op.add_column('practitioner_communication', sa.Column('language_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_communication', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_communication', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_communication', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_communication', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_communication', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_communication', 'language_system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_communication', 'language_display',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_type', sa.Enum('Organization', name='organization_reference_type'), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_id', sa.Integer(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_use', sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_practitioner_identifier_system_value', 'practitioner_identifier', ['system', 'value'])
    op.drop_column('practitioner_identifier', 'assigner')
    op.add_column('practitioner_name', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_name', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_name', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_name', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_name', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_photo', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_photo', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_photo', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_photo', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_photo', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_photo', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_use', sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('issuer_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_qualification', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_qualification', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('practitioner_qualification_identifier', sa.Column('type_version', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_type', sa.Enum('Organization', name='organization_reference_type'), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_id', sa.Integer(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_display', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_use', sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_type_system', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_type_version', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_type_code', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_type_display', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_type_text', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_type_user_selected', sa.Boolean(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_system', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_value', sa.String(), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner_identifier_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_qualification_identifier', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_qualification_identifier', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_qualification_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_qualification_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_qualification_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_practitioner_qualification_identifier_system_value', 'practitioner_qualification_identifier', ['system', 'value'])
    op.drop_column('practitioner_qualification_identifier', 'assigner')
    op.add_column('practitioner_telecom', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('practitioner_telecom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('practitioner_telecom', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('practitioner_telecom', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('practitioner_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('practitioner_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=False)
    op.alter_column('practitioner_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'questionnaire_response_item', 'questionnaire_response_answer', ['parent_answer_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaire_response_item', type_='foreignkey')
    op.alter_column('practitioner_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_telecom', 'system',
               existing_type=postgresql.ENUM('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               nullable=True)
    op.alter_column('practitioner_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_telecom', 'updated_by')
    op.drop_column('practitioner_telecom', 'created_by')
    op.drop_column('practitioner_telecom', 'updated_at')
    op.drop_column('practitioner_telecom', 'created_at')
    op.add_column('practitioner_qualification_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_practitioner_qualification_identifier_system_value', 'practitioner_qualification_identifier', type_='unique')
    op.alter_column('practitioner_qualification_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_qualification_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_qualification_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_qualification_identifier', 'updated_by')
    op.drop_column('practitioner_qualification_identifier', 'created_by')
    op.drop_column('practitioner_qualification_identifier', 'updated_at')
    op.drop_column('practitioner_qualification_identifier', 'created_at')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_period_end')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_period_start')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_value')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_system')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_type_text')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_type_display')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_type_code')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_type_version')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_type_system')
    op.drop_column('practitioner_qualification_identifier', 'assigner_identifier_use')
    op.drop_column('practitioner_qualification_identifier', 'assigner_display')
    op.drop_column('practitioner_qualification_identifier', 'assigner_id')
    op.drop_column('practitioner_qualification_identifier', 'assigner_type')
    op.drop_column('practitioner_qualification_identifier', 'type_user_selected')
    op.drop_column('practitioner_qualification_identifier', 'type_version')
    op.alter_column('practitioner_qualification', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_qualification', 'updated_by')
    op.drop_column('practitioner_qualification', 'created_by')
    op.drop_column('practitioner_qualification', 'updated_at')
    op.drop_column('practitioner_qualification', 'created_at')
    op.drop_column('practitioner_qualification', 'issuer_identifier_period_end')
    op.drop_column('practitioner_qualification', 'issuer_identifier_period_start')
    op.drop_column('practitioner_qualification', 'issuer_identifier_value')
    op.drop_column('practitioner_qualification', 'issuer_identifier_system')
    op.drop_column('practitioner_qualification', 'issuer_identifier_type_user_selected')
    op.drop_column('practitioner_qualification', 'issuer_identifier_type_text')
    op.drop_column('practitioner_qualification', 'issuer_identifier_type_display')
    op.drop_column('practitioner_qualification', 'issuer_identifier_type_code')
    op.drop_column('practitioner_qualification', 'issuer_identifier_type_version')
    op.drop_column('practitioner_qualification', 'issuer_identifier_type_system')
    op.drop_column('practitioner_qualification', 'issuer_identifier_use')
    op.alter_column('practitioner_photo', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_photo', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_photo', 'updated_by')
    op.drop_column('practitioner_photo', 'created_by')
    op.drop_column('practitioner_photo', 'updated_at')
    op.drop_column('practitioner_photo', 'created_at')
    op.alter_column('practitioner_name', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_name', 'updated_by')
    op.drop_column('practitioner_name', 'created_by')
    op.drop_column('practitioner_name', 'updated_at')
    op.drop_column('practitioner_name', 'created_at')
    op.add_column('practitioner_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_practitioner_identifier_system_value', 'practitioner_identifier', type_='unique')
    op.alter_column('practitioner_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_identifier', 'updated_by')
    op.drop_column('practitioner_identifier', 'created_by')
    op.drop_column('practitioner_identifier', 'updated_at')
    op.drop_column('practitioner_identifier', 'created_at')
    op.drop_column('practitioner_identifier', 'assigner_identifier_period_end')
    op.drop_column('practitioner_identifier', 'assigner_identifier_period_start')
    op.drop_column('practitioner_identifier', 'assigner_identifier_value')
    op.drop_column('practitioner_identifier', 'assigner_identifier_system')
    op.drop_column('practitioner_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('practitioner_identifier', 'assigner_identifier_type_text')
    op.drop_column('practitioner_identifier', 'assigner_identifier_type_display')
    op.drop_column('practitioner_identifier', 'assigner_identifier_type_code')
    op.drop_column('practitioner_identifier', 'assigner_identifier_type_version')
    op.drop_column('practitioner_identifier', 'assigner_identifier_type_system')
    op.drop_column('practitioner_identifier', 'assigner_identifier_use')
    op.drop_column('practitioner_identifier', 'assigner_display')
    op.drop_column('practitioner_identifier', 'assigner_id')
    op.drop_column('practitioner_identifier', 'assigner_type')
    op.drop_column('practitioner_identifier', 'type_user_selected')
    op.drop_column('practitioner_identifier', 'type_version')
    op.alter_column('practitioner_communication', 'language_display',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_communication', 'language_system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_communication', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_communication', 'updated_by')
    op.drop_column('practitioner_communication', 'created_by')
    op.drop_column('practitioner_communication', 'updated_at')
    op.drop_column('practitioner_communication', 'created_at')
    op.drop_column('practitioner_communication', 'language_user_selected')
    op.drop_column('practitioner_communication', 'language_version')
    op.alter_column('practitioner_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner_address', 'type',
               existing_type=postgresql.ENUM('postal', 'physical', 'both', name='address_type'),
               nullable=True)
    op.alter_column('practitioner_address', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('practitioner_address', 'updated_by')
    op.drop_column('practitioner_address', 'created_by')
    op.drop_column('practitioner_address', 'updated_at')
    op.drop_column('practitioner_address', 'created_at')
    op.drop_constraint('uq_practitioner_user_id_org_id', 'practitioner', type_='unique')
    op.drop_index(op.f('ix_practitioner_org_id'), table_name='practitioner')
    op.alter_column('practitioner', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('practitioner', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('practitioner', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'unknown', name='administrative_gender'),
               nullable=True)
    op.alter_column('practitioner', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('practitioner', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_type', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_type', 'updated_by')
    op.drop_column('organization_type', 'created_by')
    op.drop_column('organization_type', 'updated_at')
    op.drop_column('organization_type', 'created_at')
    op.drop_column('organization_type', 'coding_user_selected')
    op.drop_column('organization_type', 'coding_version')
    op.alter_column('organization_telecom', 'use',
               existing_type=sa.Enum('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='use::varchar')
    op.alter_column('organization_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_telecom', 'system',
               existing_type=sa.Enum('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='system::varchar')
    op.alter_column('organization_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_telecom', 'updated_by')
    op.drop_column('organization_telecom', 'created_by')
    op.drop_column('organization_telecom', 'updated_at')
    op.drop_column('organization_telecom', 'created_at')
    op.add_column('organization_identifier', sa.Column('assigner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_organization_identifier_system_value', 'organization_identifier', type_='unique')
    op.alter_column('organization_identifier', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_identifier', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_identifier', 'use',
               existing_type=sa.Enum('usual', 'official', 'temp', 'secondary', 'old', name='identifier_use'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='use::varchar')
    op.alter_column('organization_identifier', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_identifier', 'updated_by')
    op.drop_column('organization_identifier', 'created_by')
    op.drop_column('organization_identifier', 'updated_at')
    op.drop_column('organization_identifier', 'created_at')
    op.drop_column('organization_identifier', 'assigner_identifier_period_end')
    op.drop_column('organization_identifier', 'assigner_identifier_period_start')
    op.drop_column('organization_identifier', 'assigner_identifier_value')
    op.drop_column('organization_identifier', 'assigner_identifier_system')
    op.drop_column('organization_identifier', 'assigner_identifier_type_user_selected')
    op.drop_column('organization_identifier', 'assigner_identifier_type_text')
    op.drop_column('organization_identifier', 'assigner_identifier_type_display')
    op.drop_column('organization_identifier', 'assigner_identifier_type_code')
    op.drop_column('organization_identifier', 'assigner_identifier_type_version')
    op.drop_column('organization_identifier', 'assigner_identifier_type_system')
    op.drop_column('organization_identifier', 'assigner_identifier_use')
    op.drop_column('organization_identifier', 'assigner_display')
    op.drop_column('organization_identifier', 'assigner_id')
    op.drop_column('organization_identifier', 'assigner_type')
    op.drop_column('organization_identifier', 'type_user_selected')
    op.drop_column('organization_identifier', 'type_version')
    op.alter_column('organization_endpoint', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_endpoint', 'updated_by')
    op.drop_column('organization_endpoint', 'created_by')
    op.drop_column('organization_endpoint', 'updated_at')
    op.drop_column('organization_endpoint', 'created_at')
    op.alter_column('organization_contact_telecom', 'use',
               existing_type=sa.Enum('home', 'work', 'temp', 'old', 'mobile', name='contact_point_use'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='use::varchar')
    op.alter_column('organization_contact_telecom', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact_telecom', 'system',
               existing_type=sa.Enum('phone', 'fax', 'email', 'pager', 'url', 'sms', 'other', name='contact_point_system'),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='system::varchar')
    op.alter_column('organization_contact_telecom', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_contact_telecom', 'updated_by')
    op.drop_column('organization_contact_telecom', 'created_by')
    op.drop_column('organization_contact_telecom', 'updated_at')
    op.drop_column('organization_contact_telecom', 'created_at')
    op.alter_column('organization_contact', 'address_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_contact', 'address_type',
               existing_type=sa.Enum('postal', 'physical', 'both', name='address_type'),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='address_type::varchar')
    op.alter_column('organization_contact', 'address_use',
               existing_type=sa.Enum('home', 'work', 'temp', 'old', 'billing', name='address_use'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='address_use::varchar')
    op.alter_column('organization_contact', 'name_use',
               existing_type=sa.Enum('usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden', name='human_name_use'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='name_use::varchar')
    op.alter_column('organization_contact', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_contact', 'updated_by')
    op.drop_column('organization_contact', 'created_by')
    op.drop_column('organization_contact', 'updated_at')
    op.drop_column('organization_contact', 'created_at')
    op.drop_column('organization_contact', 'purpose_user_selected')
    op.drop_column('organization_contact', 'purpose_version')
    op.alter_column('organization_alias', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_alias', 'updated_by')
    op.drop_column('organization_alias', 'created_by')
    op.drop_column('organization_alias', 'updated_at')
    op.drop_column('organization_alias', 'created_at')
    op.alter_column('organization_address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization_address', 'type',
               existing_type=sa.Enum('postal', 'physical', 'both', name='address_type'),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='type::varchar')
    op.alter_column('organization_address', 'use',
               existing_type=sa.Enum('home', 'work', 'temp', 'old', 'billing', name='address_use'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='use::varchar')
    op.alter_column('organization_address', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization_address', 'updated_by')
    op.drop_column('organization_address', 'created_by')
    op.drop_column('organization_address', 'updated_at')
    op.drop_column('organization_address', 'created_at')
    op.alter_column('organization', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('organization', 'org_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organization', 'partof_identifier_period_end')
    op.drop_column('organization', 'partof_identifier_period_start')
    op.drop_column('organization', 'partof_identifier_value')
    op.drop_column('organization', 'partof_identifier_system')
    op.drop_column('organization', 'partof_identifier_type_user_selected')
    op.drop_column('organization', 'partof_identifier_type_text')
    op.drop_column('organization', 'partof_identifier_type_display')
    op.drop_column('organization', 'partof_identifier_type_code')
    op.drop_column('organization', 'partof_identifier_type_version')
    op.drop_column('organization', 'partof_identifier_type_system')
    op.drop_column('organization', 'partof_identifier_use')
    op.execute('DROP SEQUENCE IF EXISTS allergy_intolerance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS appointment_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS audit_event_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS care_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS claim_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS condition_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS coverage_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS device_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS diagnostic_report_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS document_reference_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS encounter_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS episode_of_care_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS healthcare_service_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS immunization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS insurance_plan_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS invoice_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS location_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS medication_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS observation_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS organization_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS patient_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS practitioner_role_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS procedure_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS provenance_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS questionnaire_response_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS related_person_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS schedule_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS service_request_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS slot_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS specimen_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS task_pub_seq')
    op.execute('DROP SEQUENCE IF EXISTS vitals_pub_seq')
    # ### end Alembic commands ###
