from app.schemas.appointment.input import (
    AppointmentCreateSchema,
    AppointmentPatchSchema,
    AppointmentIdentifierInput,
    AppointmentClassInput,
    AppointmentServiceCategoryInput,
    AppointmentServiceTypeInput,
    AppointmentSpecialtyInput,
    AppointmentReasonInput,
    AppointmentSupportingInformationInput,
    AppointmentSlotInput,
    AppointmentBasedOnInput,
    AppointmentReplacesInput,
    AppointmentVirtualServiceInput,
    AppointmentAccountInput,
    AppointmentNoteInput,
    AppointmentPatientInstructionInput,
    AppointmentParticipantTypeInput,
    AppointmentParticipantInput,
    AppointmentRequestedPeriodInput,
    RecurrenceTemplateInput,
    RecurrenceWeeklyTemplateInput,
    RecurrenceMonthlyTemplateInput,
    RecurrenceYearlyTemplateInput,
)
from app.schemas.appointment.response import (
    FHIRAppointmentSchema,
    FHIRAppointmentBundle,
    FHIRAppointmentBundleEntry,
    FHIRAppointmentParticipant,
    FHIRRecurrenceTemplate,
    FHIRRecurrenceWeeklyTemplate,
    FHIRRecurrenceMonthlyTemplate,
    PaginatedAppointmentResponse,
    PlainAppointmentResponse,
    PlainAppointmentIdentifier,
    PlainAppointmentClass,
    PlainAppointmentServiceCategory,
    PlainAppointmentServiceType,
    PlainAppointmentSpecialty,
    PlainAppointmentReason,
    PlainAppointmentSupportingInformation,
    PlainAppointmentSlot,
    PlainAppointmentBasedOn,
    PlainAppointmentReplaces,
    PlainAppointmentVirtualService,
    PlainAppointmentAccount,
    PlainAppointmentNote,
    PlainAppointmentPatientInstruction,
    PlainAppointmentParticipantType,
    PlainAppointmentParticipant,
    PlainAppointmentRequestedPeriod,
    PlainWeeklyTemplate,
    PlainMonthlyTemplate,
    PlainYearlyTemplate,
    PlainRecurrenceTemplate,
)

__all__ = [
    # Input
    "AppointmentCreateSchema", "AppointmentPatchSchema",
    "AppointmentIdentifierInput", "AppointmentClassInput",
    "AppointmentServiceCategoryInput", "AppointmentServiceTypeInput", "AppointmentSpecialtyInput",
    "AppointmentReasonInput",
    "AppointmentSupportingInformationInput", "AppointmentSlotInput", "AppointmentBasedOnInput",
    "AppointmentReplacesInput", "AppointmentVirtualServiceInput", "AppointmentAccountInput",
    "AppointmentNoteInput", "AppointmentPatientInstructionInput",
    "AppointmentParticipantTypeInput", "AppointmentParticipantInput", "AppointmentRequestedPeriodInput",
    "RecurrenceTemplateInput", "RecurrenceWeeklyTemplateInput",
    "RecurrenceMonthlyTemplateInput", "RecurrenceYearlyTemplateInput",
    # Response
    "FHIRAppointmentSchema", "FHIRAppointmentBundle", "FHIRAppointmentBundleEntry",
    "FHIRAppointmentParticipant",
    "FHIRRecurrenceTemplate", "FHIRRecurrenceWeeklyTemplate", "FHIRRecurrenceMonthlyTemplate",
    "PaginatedAppointmentResponse", "PlainAppointmentResponse",
    "PlainAppointmentIdentifier", "PlainAppointmentClass",
    "PlainAppointmentServiceCategory", "PlainAppointmentServiceType", "PlainAppointmentSpecialty",
    "PlainAppointmentReason",
    "PlainAppointmentSupportingInformation", "PlainAppointmentSlot", "PlainAppointmentBasedOn",
    "PlainAppointmentReplaces", "PlainAppointmentVirtualService", "PlainAppointmentAccount",
    "PlainAppointmentNote", "PlainAppointmentPatientInstruction",
    "PlainAppointmentParticipantType", "PlainAppointmentParticipant", "PlainAppointmentRequestedPeriod",
    "PlainWeeklyTemplate", "PlainMonthlyTemplate", "PlainYearlyTemplate", "PlainRecurrenceTemplate",
]
