from app.schemas.appointment.input import (
    AppointmentCreateSchema,
    AppointmentPatchSchema,
    AppointmentIdentifierInput,
    AppointmentServiceCategoryInput,
    AppointmentServiceTypeInput,
    AppointmentSpecialtyInput,
    AppointmentReasonCodeInput,
    AppointmentReasonReferenceInput,
    AppointmentSupportingInformationInput,
    AppointmentSlotInput,
    AppointmentBasedOnInput,
    AppointmentParticipantTypeInput,
    AppointmentParticipantInput,
    AppointmentRequestedPeriodInput,
    RecurrenceTemplateInput,
    RecurrenceWeeklyTemplateInput,
    RecurrenceMonthlyTemplateInput,
    RecurrenceYearlyTemplateInput,
)
from app.schemas.appointment.response import (
    FHIRAppointmentSchema,
    FHIRAppointmentBundle,
    FHIRAppointmentBundleEntry,
    FHIRAppointmentParticipant,
    PaginatedAppointmentResponse,
    PlainAppointmentResponse,
    PlainAppointmentIdentifier,
    PlainAppointmentServiceCategory,
    PlainAppointmentServiceType,
    PlainAppointmentSpecialty,
    PlainAppointmentReasonCode,
    PlainAppointmentReasonReference,
    PlainAppointmentSupportingInformation,
    PlainAppointmentSlot,
    PlainAppointmentBasedOn,
    PlainAppointmentParticipantType,
    PlainAppointmentParticipant,
    PlainAppointmentRequestedPeriod,
    PlainWeeklyTemplate,
    PlainMonthlyTemplate,
    PlainYearlyTemplate,
    PlainRecurrenceTemplate,
)

__all__ = [
    # Input
    "AppointmentCreateSchema", "AppointmentPatchSchema",
    "AppointmentIdentifierInput",
    "AppointmentServiceCategoryInput", "AppointmentServiceTypeInput", "AppointmentSpecialtyInput",
    "AppointmentReasonCodeInput", "AppointmentReasonReferenceInput",
    "AppointmentSupportingInformationInput", "AppointmentSlotInput", "AppointmentBasedOnInput",
    "AppointmentParticipantTypeInput", "AppointmentParticipantInput", "AppointmentRequestedPeriodInput",
    "RecurrenceTemplateInput", "RecurrenceWeeklyTemplateInput",
    "RecurrenceMonthlyTemplateInput", "RecurrenceYearlyTemplateInput",
    # Response
    "FHIRAppointmentSchema", "FHIRAppointmentBundle", "FHIRAppointmentBundleEntry",
    "FHIRAppointmentParticipant",
    "PaginatedAppointmentResponse", "PlainAppointmentResponse",
    "PlainAppointmentIdentifier",
    "PlainAppointmentServiceCategory", "PlainAppointmentServiceType", "PlainAppointmentSpecialty",
    "PlainAppointmentReasonCode", "PlainAppointmentReasonReference",
    "PlainAppointmentSupportingInformation", "PlainAppointmentSlot", "PlainAppointmentBasedOn",
    "PlainAppointmentParticipantType", "PlainAppointmentParticipant", "PlainAppointmentRequestedPeriod",
    "PlainWeeklyTemplate", "PlainMonthlyTemplate", "PlainYearlyTemplate", "PlainRecurrenceTemplate",
]
